redhat-developer/service-binding-operator

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
The resource details are looked up inside the CSV spec. For example, consider this CSV file:
https://github.com/operator-framework/community-operators/blob/0230c07c33ae36272151f918ad7c87d62ae13ee4/upstream-community-operators/etcd/etcdoperator.v0.9.4.clusterserviceversion.yaml#L232
Line no. 232 to 234 is what is used to identify the CSV.
=> Clarify the API

deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
`make lint`  is throwing error 
```
./deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
13:29     error    trailing spaces  (trailing-spaces)
```
This patch removes those spaces.
=> Fix for trailing spaces lint error

Makefile
The `test-unit` target runs unit tests. The `e2e` directory is excluded.
=> Create Makefile target to run unit tests

Makefile
In the CI environment, the default location is read-only. The cache needs to write access.
=> Set GOCACHE for `go list` command

OWNERS, test/OWNERS
This is required for prow tide plugin:
https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md
=> Add OWNERS list

Makefile
The uuidgen produce captial letters in Mac
=> Convert namespace to lowercase

deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.package.yaml, deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.servicebindingrequests.crd.yaml, deploy/olm-catalog/service-binding-operator/0.0.1/service-binding-operator.v0.0.1.clusterserviceversion.yaml
Source the following:
```
OPERATOR_DIR=0.0.1
QUAY_NAMESPACE=redhat-developer
PACKAGE_NAME=service-binding-operator
PACKAGE_VERSION=0.0.1
TOKEN="basic c2----I5"
```
Run
```
operator-courier verify --ui_validate_io 0.0.1
```
Run 
```
operator-courier push "$OPERATOR_DIR" "$QUAY_NAMESPACE" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$TOKEN"
```
This would push the artifacts into a Quay App Registry
https://quay.io/application/redhat-developer/service-binding-operator?tab=releases
After that, create an OperatorSource
```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
name: redhat-developer-operators
namespace: openshift-marketplace
spec:
type: appregistry
endpoint: https://quay.io/cnr
registryNamespace: redhat-developer
```
This should reconcile, and consequently the operator …
=> Package operator as a marketplace operator

deploy/role.yaml
The controller would need to read the backing-service CR that would be bound. Since there is no way to know the API group or the resource in advance, we would have to let the service account `get` all resources in the namespace.
=> Allow GET on all namespace-scoped CRs

Makefile
Renaming `test-e2e` to `test-unit`, as incorrect name was given to unit test target.
=> Small makefile fixes

Dockerfile, Makefile, pkg/controller/servicebindingrequest/servicebindingrequest_controller.go
- Adding this Dockerfile until we have automated mirroring of builds happening from openshift CI
- I plan to integrate this with quay.io/redhat-developer
- Added `make build`
=> Add Dockerfile 

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
Using the instance name we can uniquely identify the CR. It would point to the correct instance because we can have many instances. But we need to be particular about the instance. Labels might match to more than one instance so label selectors would not be a good approach.
=> Add objectName selector

manifests/service-binding-operator.package.yaml, manifests/service-binding-operator.v0.0.6.clusterserviceversion.yaml
Since these are dev releases, I am avoiding `replaces`. Once we our first stable release done, we will support upgrades
=> Release 0.0.6

Makefile
- The help target shows sections of the target. Colorization for targets
in the output helps to recognize targets.
- Remove the `./` prefix from targets where a path needs to be specified. This causes some target
not properly rendered in the help output.
- Remove `vendor` as a dependency and it is already part of the source tree.
Current help output:
=> Create a more readable help target

Makefile
This PR adds `courier` target a sub target in lint, `local` target to run operator locally and `clean` target to clean cached directory. `local` target has some dependency targets added in this PR.
=> Add operator-courier lint, run operator locally and cleaning targets

manifests/service-binding-operator.package.yaml
This PR provides two channels - `dev` and `stable`. In the future, we can have these channels pointing to different ClusterServiceVersion respectively. For development purpose, we can use the dev channel and a stable release can be under the stable channel.  By default the cannel is the `dev` channel.
=> Change channel from stable to alpha

pkg/controller/servicebindingrequest/retriever_test.go
- Avoid global variable
- Make each sub test to run independently
=> Refactor test to use sub tests

pkg/controller/servicebindingrequest/planner/planner.go, pkg/controller/servicebindingrequest/planner/planner_test.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go
Moving into a separate package will make re-usability easier.
=> Move planner into a separate package

pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/mocks/mocks.go
Refer  - https://jira.coreos.com/browse/ODC-1242
Adding support for configMap through the following way
```
x-descriptors:
- urn:alm:descriptor:servicebinding:env:object:configmap:username
- urn:alm:descriptor:servicebinding:env:object:configmap:password
```
=> Adding ConfigMap support for the controller

openshift-ci/Dockerfile.tools
This PR adds `jq` among the tools installed in the `root` container for OpenShift CI.
The `jq` is a dependency for https://github.com/redhat-developer/service-binding-operator/pull/82.
The tool needs to be added and merged in a separated PR prior merging the actual PR that depends on it, because of how OpenShift CI and Prow works.
=> Install jq to root container for OpenShift CI.

Dockerfile, openshift-ci/Dockerfile.tools
.. to unblock PR/master builds which are now failing 
```
8/11/2019, 3:59:28 AMwarning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-11.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
8/11/2019, 3:59:28 AMPublic key for epel-release-7-11.noarch.rpm is not installed
8/11/2019, 3:59:28 AMRetrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
8/11/2019, 3:59:28 AMImporting GPG key 0xF4A80EB5: Userid : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>" Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5 Package : centos-release-7-6.1810.2.el7.centos.x86_64 (@CentOS) From : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
8/11/2019, 3:59:28 AMRunning transaction check
8/11/2019, 3:59:28 AMRunning transaction test
8/11/2019, 3:59:28 …
```
=> Ignore broken packages for the time being

README.md
**Why**
Creation of `ServiceBindingRequest` requires `mountPathPrefix` field to be added in the spec.
=> Add mountPathPrefix spec field in the example

pkg/controller/servicebindingrequest/planner/planner.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/resourcepoll/wait.go, pkg/utils/wait_utils.go
This PR adds utility functions to wait for k8s/Openshift resources.
**Why**
There are some gitOps use cases where `servicebindingrequest` would need to wait for resources(such as Deployment, backend Operator CR). 
**What is added**
This PR adds following two wait functions
1. `WaitUntilResourceFound` -> Function to wait for particular resource to be created. 
2. `WaitUntilResourcesFound` -> Function to wait for list of resources to be created.
**To Do**
=> Add wait in reconcile loop.

Dockerfile, Makefile, openshift-ci/Dockerfile.tools
- https://bugzilla.redhat.com/show_bug.cgi?id=1739804
- Pushed branch to redhat-developer/.. so that it triggers a build on https://quay.io/repository/redhat-developer/app-binding-operator/build which is driven from the `/Dockerfile`
=> Add lint back

README.md, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/mocks/mocks.go
This was a feedback we received from Jessica during an API review. We don't really need the long strings.
=> Make the annotations shorter

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go, pkg/controller/servicebindingrequest/common.go, pkg/controller/servicebindingrequest/controller.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/reconciler_whitebox_test.go
- If the user updated the CR to have a `triggerRebinding` to true, a reconcile is triggered where the value is set to`false`. 
- The predicate takes care of rejecting the event if the event was generated because `triggerRebinding` was set from `false` to `true`.
In no scenario, does the controller never set it to `true`.
```
metadata:
namespace: sbose
spec:
matchLabels:
connects-to: postgres
environment: demo
group: apps.openshift.io
version: v1
resource: deploymentconfigs
triggerRebinding: true
kind: Database
resourceRef: demo-database
```
This would come handy when custom resources not owned by the operator …
=> Add OPTIONAL triggerRebinding field in the Spec

test/e2e/servicebindingrequest_test.go
Adding `time.Sleep` on `retry` method used in end-to-end tests.
=> Added in sleep statement that is referenced, but is missing

examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
Small correction in the readme of this example: Binding an Imported app to an In-cluster Operator Managed PostgreSQL Database
=> Correct small errors and a link in readme of an example. 

examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/Makefile, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/backing-db-operator-source.yaml, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/create-db-instance.yaml, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/namespace.yaml, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-operator-source.yaml, examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/service-binding-request.yaml
This pull request accomplishes a couple of things:
First, it adds a Makefile (with an updated README) to make it easier for users to perform the steps necessary to load and run the example.
Second, it brings this example into alignment with the RDS off cluster example which also makes use of a Makefile.
=> Update the original (in-cluster) example to include a Makefile

examples/bind_imported_app_to_incluster_operator_managed_PostgreSQL_db/README.md
README update must have been missed when we changed the app name.
=> Updated reference to deployed app in example README

Makefile, pkg/controller/servicebindingrequest/annotations.go, pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/common.go, pkg/controller/servicebindingrequest/olm.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/mocks/fake.go, test/mocks/mocks.go
Refactoring reconciliation process to only update objects as last step. Status of `ServiceBindingRequest` is kept as a local variable, and updated as the reconciliation process goes, and attempts to update object status will happen in case of error, or at the end of reconciliation.
This PR addresses errors on updating objects that have been modified, and considerably reduces the amount of API calls during reconciliation.
Furthermore, fixing panic triggered on `planner.go:66` due a `nil` variable returned, covering issue scenario with unit-test. The test is asserting the reconciliation processes will return error and cause re-queue in case of expected resources are not found.
=> Object Updates as Last Reconciliation Step

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go
Ensure the following is added only once, but updated on subsequent reconciles.
```
spec:
containers:
- resources: {}
terminationMessagePath: /dev/termination-log
name: app2
env:
- name: lastbound
value: '2019-09-19T19:57:06-04:00'
```
=> Ensure lastbound env key is not added multiple times

hack/examples-commons.sh
This pull request eliminates this feedback to users - which might cause confusion for new users:
```
==   -  STEP 1/5 -   ==  
-  Cleanup process  -  
error: unable to recognize "../../hack/yamls/service-mesh-control-plane.yaml": no matches for kind "ServiceMeshControlPlane" in version "maistra.io/v1"
error: unable to recognize "../../hack/yamls/service-mesh-member-roll.yaml": no matches for kind "ServiceMeshMemberRoll" in version "maistra.io/v1"
Error from server (NotFound): error when deleting "../../hack/yamls/knative-serving.yaml": namespaces "knative-serving" not found
unable to recognize "../../hack/yamls/knative-serving.yaml": no matches for kind "KnativeServing" in version "serving.knative.dev/v1alpha1"
```
=> Minor changes to improve feedback to users when running examples

openshift-ci/Dockerfile.tools
This PR updates the Dockerfile.tools to update version of: 
`go version go1.13.1 linux/amd64`
`kubectl to auto-update when the stable version is released`
`operator-sdk version: v0.10.0`
=> Update golang, kubectl, and operator-sdk version to latest in CI

go.mod
After upgrading to go 1.13 from 1.12, the go version is added to go.mod.
It seems that this is ignored in 1.12, so everything should work fine.
=> Add go version in go.mod

examples/commons.mk
The subscription needs to be deleted before the operator source.
=> Fix operator uninstallers in example commons.

Makefile
This is for running e2e test in cluster way, an alternative to run tests locally on the operator.
=> Add test-e2e-image target to run test on operator image

deploy/role.yaml, manifests/service-binding-operator.v0.0.20.clusterserviceversion.yaml
The backing CRs are updated with an SBR annotation at the time of reconcile. This PR adds the service account privilege to enable that.
Fixes 
```
{"level":"info","ts":1571751848.8616478,"logger":"binder","msg":"Reading back updated object...","Obj.Name":"e2e-application","Obj.Kind":"Deployment"}
2019-10-22T13:44:08.865Z    INFO    servicebindingrequest    Updating resource annotations...    {"SBR.Namespace": "test-namespace-527580c4-2b32-46d0-a1f0-a0bd2e0643b8", "SBR.Name": "e2e-service-binding-request", "Resource.GVK": "postgresql.baiju.dev/v1alpha1, Kind=Database", "Resource.Namespace": "test-namespace-527580c4-2b32-46d0-a1f0-a0bd2e0643b8", "Resource.Name": "e2e-db-testing"}
2019-10-22T13:44:09.048Z    ERROR    servicebindingrequest    unable to set/update annotations in object …
```
=> Enable the 'update' privilege for the service account so that CRs can be updated.

Makefile, hack/e2e-log-parser.sh
This hack script replaces the `sed` pipeline in the main `Makefile` by a simpler hack script provided by @otaviof
=> Use @otaviof's hack script to get operator log from e2e tests.

pkg/controller/servicebindingrequest/reconciler.go
I've noticed infinite reconciles & panics because addition of the annotation on the DC/D keeps failing. This PR safely removes addition of the annotation. 
Since we do not make use of the annotation ( we don't watch DCs/Ds anyway ), not adding the annotation has no adverse impact.
=> Skip adding annotations to the Deployment

test/e2e/servicebindingrequest_test.go
If secret not found, then the test should stop and not continue further. Thus, we should use `require` instead of `assert`.
=> changes assert to require

examples/knative_postgresql_customvar/Makefile, examples/knative_postgresql_customvar/README.md, examples/knative_postgresql_customvar/service-binding-request.yaml, examples/knative_postgresql_customvar/serving.yaml
Update the Knative example to be in synch with OpenShift 4.3 and to replace the use of labels with resourceRef in the ApplicationSelector.
* The ServiceBindingSelector is updated to use a resourcceRef and not labels as we are discouraging the use of labels.
* A new yaml file (serving.yaml) is added - this is necessary to install Knative after the operators are installed.
* The README and Makefile are updated to reflect the other changes.
* To test, follow the steps in the README file on an OpenShift 4.3 cluster.
=> Update the Knative example to be in synch with OpenShift 4.3

pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go
Fix #264 
Changes are in retriever.go to check if variables for customEnvVar are already base 64-encoded and decoding them if they are, since all variables are base 64 encoded when written to the binding request secret.
Did not add new tests, just checked that double base 64 encoding does not happen for customEnvVar retrieved from a secret and no changes are made when variables are retrieved directly from status.
=> Fix double base64 encoding for customEnvVar (#264)

examples/nodejs_awsrds_varprefix/README.md, examples/nodejs_awsrds_varprefix/namespace.yaml, examples/nodejs_awsrds_varprefix/service-binding-request.nodejs-app.yaml, examples/nodejs_awsrds_varprefix/service-binding-request.shell-app.yaml
The goals of this pull request are to get the RDS example up to date with OpenShift's use of Deployments, and up to date with the Service Binding Operator's use of reeeesrouceRef for Application selectors. 
The README, Makefile. and ServiceBindingRequest definitions are updated. 
The example was verified by following the steps in the README.
=> Update RDS example to match 4.3 Deployments and SBO use of resourceRefs

pkg/controller/servicebindingrequest/custom_env_parser_test.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, pkg/controller/servicebindingrequest/secret.go, pkg/controller/servicebindingrequest/secret_test.go
Fix for https://github.com/redhat-developer/service-binding-operator/issues/272
=> Reuse retrieve.Cache for customEnvParser in secret.go

.travis.yml
Travis CI fails [1] because of https://github.com/golang/go/issues/35827, and the workaround is either clean `GOFLAGS` and keep `go test -mod=vendor ...` as it is, or remove the `-mod=vendor` flag from `go test` and keep `GOFLAGS` properly configured.
This change implements the latter.
[1] https://travis-ci.org/redhat-developer/service-binding-operator/builds/623623393?utm_source=github_status&utm_medium=notification.
Edit: rewording.
=> Implement workaround for GOFLAGS

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
The `matchLabels` was treated as optional, but not really marked it properly.
Change the spec.
The existing test should cover it.
=> Mark matchLabels as optional

pkg/controller/servicebindingrequest/reconciler.go
Fixing Issue #287, reporting finalizers are getting repeated.
Probing if finalizer is already present before appending.
Regular end-to-end and unit-tests are covering this scenario already.
=> Avoiding Repeated Finalizers

go.mod, go.sum, vendor/modules.txt
With the current version specified in go.mod and an empty cache, the following
error happens:
$ go mod vendor
go: github.com/openshift/api@v3.9.1-0.20190424152011-77b8897ec79a+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
This patch replaces it with a valid pseudo-version encoding
the same commit specified in the original.
=> Fixes go mod invalid pseudo-version error

Makefile
After making a manual release, the version number should be incremented.
=> Increment operator version to 0.0.24

Makefile
On installing the operator there was an ImagePullBackOff error due to improper tagging of the operator image in the REPLACE_IMAGE in the csv file, and hence the operator was not getting installed.
=> Do proper tagging for operator images

test/e2e/servicebindingrequest_test.go
The e2e scenario is described as `scenario-csv-db-app-sbr` but there is no csv step in `ServiceBindingRequest(t, []Step{SBRStep, AppStep, DBStep})`.
Add `CSVStep` in scenario.
`make test-e2e`
=> Add CSVstep in e2e scenario-csv-db-app-sbr

test/mocks/mocks.go
CSV mock is broken which causing test failure: 
```
Error:      	Received unexpected error:
ClusterServiceVersion.operators.coreos.com "cluster-service-version-6129484611666145821" is invalid: [spec.install.spec.deployments.spec.template.spec.containers: Invalid value: "null": spec.install.spec.deployments.spec.template.spec.containers in body must be of type array: "null", spec.install.spec.deployments.spec.selector: Invalid value: "null": spec.install.spec.deployments.spec.selector in body must be of type object: "null"]
Test:       	TestAddSchemesToFramework/end-to-end/scenario-csv-app-db-sbr
FAIL
```
Issue: https://github.com/redhat-developer/service-binding-operator/issues/306
Updating csv mock.
make test-e2e
After changes: 
```
PASS: TestAddSchemesToFramework/end-to-end (43.03s)
--- …
```
=> Update csv mock, add selector and containers.

go.mod, go.sum, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/controller/servicebindingrequest/binding.go, pkg/controller/servicebindingrequest/binding_test.go, pkg/controller/servicebindingrequest/plan_decoupled.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/related_resources.go, pkg/controller/servicebindingrequest/retrieve_decoupled.go, pkg/controller/servicebindingrequest/retriever_test.go, pkg/controller/servicebindingrequest/secret.go, pkg/controller/servicebindingrequest/secret_test.go, test/mocks/fake.go, vendor/modules.txt
This PR is a preparation for binding multiple backing services with the specified application.
It introduces the ServiceBinder component, which is responsible for orchestrating the low-level components handling operational tasks such as updating Kubernetes resources related to the Service Binding Request.
ServiceBinder is still incomplete in this PR, but the changes made in the current tests should prove whether the existing functionality is still covered.
Since it is incomplete, its tests are currently skipped and will be enabled when all dependencies are in place.
=> pre-req refactor to support multiple backing services

Makefile
The oc cli is not installed under openshift-ci/Dockerfile.tools . Replace oc with kubectl
Follow up the cron job history here https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/periodic-ci-redhat-developer-service-binding-operator-master-dev-release
=> oc is not installed in the openshift-ci in our cluster

openshift-ci/Dockerfile.tools
Update golang version to 1.13.7 and operator-sdk version to 0.15.1 in the OpenShift-CI
=> Update golang and operator-sdk version in OpenShift CI

Makefile
This is required for scripts calling from Makefile
Ref.
https://stackoverflow.com/questions/23843106/how-to-set-child-process-environment-variable-in-makefile
This is required for scripts calling from Makefile
<< What has been changed in order to achieve "story's" objective? >>
=> Export all env variables

Makefile, deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml
Improve rendering of the operator entry on OperatorHub.io
added `createdAt`, `support`, `repository` annotations to improve UX on OperatorHub.io
In addition that, added link to the blog post.
The fields listed in in https://github.com/operator-framework/community-operators/blob/master/docs/required-fields.md
are mandatory for a good user experience/proper rendering of operator info at operatorhub.io
`make push-to-manifest-repo` should generate CSV with additional fields
=> added `createdAt`, `support`, `repository` annotations to improve UX on OperatorHub.io

examples/commons.mk, examples/java_postgresql_customvar/README.md, examples/knative_postgresql_customvar/README.md, examples/nodejs_awsrds_varprefix/README.md, examples/nodejs_postgresql/README.md, hack/examples-commons.sh
Previously, before service binding operator became part of the community operators there was a need to add it to the internal OperatorHub via an Operator Source. Now it is not necessary.
* The use of Operator Source for installing of the Service Binding Operator is removed.
* The SBO's subscription is changed to the community version.
Manually follow the examples' step-by-step instructions.
=> Update examples to use community version of the SBO.

.travis.yml
The travis.ci passes even if any of the make commands fails - tha failures are thrown away.
All the `make` commands under the `if`condition in the `.travis.yaml`'s `script` are executed in a way, which returns a non-zero exit code, in case any of those fails.
=> Propagate Makefile failures to the travis.

.travis.yml
Follow-up to #337 
The current travis script fails with the following:
```
$ if [ "$TRAVIS_BRANCH" = "master" ]; then make merge-to-master-release && \ make push-to-manifest-repo && \ make push-bundle-to-quay || exit 1 fi
/home/travis/.travis/functions: eval: line 110: syntax error: unexpected end of file
The command "if [ "$TRAVIS_BRANCH" = "master" ]; then make merge-to-master-release && \ make push-to-manifest-repo && \ make push-bundle-to-quay || exit 1 fi" exited with 1.
```
The  `\` symbols are removed and `;` is added at the end of the `then` block to fix the problem.
=> Fix .travis.yaml

hack/dev-release.sh
Explicitly specify the namespace.
This is required in OpenShift CI. Otherwise, these kinds of error will appear:
```
Error from server (NotFound): error when creating "./output.json": namespaces "ci-op-rs66vgqc" not found
```
Use default namespace.
=> Use default namespace for example CR

pkg/controller/servicebindingrequest/binder_test.go
Refactor knative test
`go test ./pkg/controller/servicebindingrequest -run TestKnativeServicesContractWithBinder -v` 
or
`make test-unit` to run all the unit tests
=> Refactor knative test: abridge test by removing unnecessary assertion.

pkg/controller/servicebindingrequest/binding_test.go, pkg/controller/servicebindingrequest/retrieve_decoupled.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/secret.go
This PR adds a test case for the #354, and provides a solution for it without taking in consideration changes in the custom environment variables syntax to accommodate the multiple services feature.
The SBR's secret data was being produced prior to persisting it in the API server whenever a service binding was being reconciled but the underlying data doesn't change after it is initially read. 
This PR moves CustomEnvParser from secret to retriever (which owns the visited paths used as input for the CustomEnvParser), and generates the final secret data right after services have been discovered.
=> Use visited paths as input for CustomEnvParser instead of processed environment variables

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go, pkg/controller/servicebindingrequest/bind_custom_resources.go, pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/planner.go, pkg/controller/servicebindingrequest/planner_test.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, pkg/controller/servicebindingrequest/secret_test.go, test/e2e/servicebindingrequest_test.go, test/mocks/fake.go, test/mocks/mocks.go
fixes #314 
1. Create a new nodejs app in namespace `sbose`
2. Create a new Database in namespace `sbose-x`
3. Create a ServiceBindingRequest
```
metadata:
name: nodejs-rest-http-crud-dc-demo-database-postgresql-d
namespace: sbose
spec:
group: apps.openshift.io
resource: deploymentconfigs
resourceRef: nodejs-rest-http-crud
version: v1
kind: Database
namespace: sbose-x
resourceRef: demo-database
detectBindingResources: true
status:
applicationObjects:
- sbose/nodejs-rest-http-crud
bindingStatus: BindingSuccess
conditions:
- lastHeartbeatTime: 2020-02-20T21:52:51Z
lastTransitionTime: 2020-02-20T21:47:30Z
status: "True"
type: Ready
secret: …
```
=> Support binding to a backing Service in a different namespace

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go, pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/binding_test.go, pkg/controller/servicebindingrequest/planner.go, pkg/controller/servicebindingrequest/planner_test.go, pkg/controller/servicebindingrequest/sbrcontroller_test.go, test/e2e/servicebindingrequest_test.go, test/mocks/mocks.go
If the following SBR is created with a populated `BackingServiceSelectors`... 
```
metadata:
name: nodejs-rest-http-crud-d-demo-database-postgresql-d
namespace: sbose
spec:
group: apps
resource: deployments
resourceRef: nodejs-rest-http-crud
version: v1
backingServiceSelectors:
- group: postgresql.baiju.dev
kind: Database
resourceRef: demo-database
```
Post reconciliation, magically, the empty `BackingServiceSelector` also shows up:
```
metadata:
creationTimestamp: '2020-03-09T04:44:50Z'
finalizers:
- finalizer.servicebindingrequest.openshift.io
generation: 3
name: nodejs-rest-http-crud-d-demo-database-postgresql-d …
```
=> Avoid appearance of empty fields

pkg/controller/servicebindingrequest/olm.go, pkg/controller/servicebindingrequest/olm_test.go
Parsing the annotations into the data structures which contained spec|status descriptors had a bug where only one spec descriptor and one status descriptor was being persisted irrespective of the total number of annotations present.
Example, the following 
```
"servicebindingoperator.redhat.io/status.dbCredentials-db.password": "binding:env:object:secret",
"servicebindingoperator.redhat.io/spec.dbName":                      "binding:env:attribute",
"servicebindingoperator.redhat.io/spec.image":                       "binding:env:attribute",
"servicebindingoperator.redhat.io/status.dbConfigMap-db.host":       "binding:env:object:configmap",
```
was being mapped to only one spec descriptor and one status descriptor, instead of two each.
Fix the 
```
func …
```
=> (bug) Fix normalization of annotations to CRDDescription

pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/reconciler_test.go
https://issues.redhat.com/browse/APPSVC-248
###
testing:
`make test-unit`
or
`go test ./pkg/controller/servicebindingrequest -run TestReconcilerReconcileWithConflictingAppSelc -v `
=> Add test for conflicting resource ref and labels

hack/boilerplate.go.txt
As the `operator-sdk generate open-api` is deprecated this PR adds a boilerplate file for open api gen.
Refer https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#openapi 
Boilerplate file at - https://github.com/kubernetes/kube-openapi/blob/master/boilerplate/boilerplate.go.txt
=> Add boilerplate file as operator-sdk generate open-api is deprecated

cmd/manager/main.go
Remove osappsv1 from the scheme and as a dependency as now we use Unstructured and osappsv1 was added for deploymentconfigs. (https://github.com/redhat-developer/service-binding-operator/pull/90/files#diff-a8480c104199c9b04be874f1d87ef9abR44)
=> Remove osappsv1 from scheme

.travis.yml, Makefile, hack/dev-release.sh, test/operator-hub/subscription.yaml
Also specify the version in the subscription with Manual upgrade.
Fixes #390
The current issue is coming because we decrement the version of the Quay application bundle. Since we are using a periodic job there is a chance for false positives if we merge to master within short intervals.
These issues are addressed with these changes:
1. Include all past releases in the Quay application bundle (Without this only the latest will be available in the catalog)
2. Specify the start version of CSV and use Manual mode for install plan approval (This prevent automatic upgrade)
=> Include past releases in the bundle

Makefile
This is required to fix Dev release.
"It looks like OperatorSource is always pulling the latest version from the Quay application registry. Since we can't remove releases from Quay, we should increment the version."
=> Increment version to 0.1.1

pkg/controller/servicebindingrequest/olm.go, pkg/controller/servicebindingrequest/olm_test.go, pkg/controller/servicebindingrequest/sbrcontroller.go
Currently the operator will throw error `"olm","msg":"on listting CSVs","error":"the server could not find the requested resource"` if CSV CRD is not installed.
Handle these errors will make service binding operator work with less dependency(With SBR CRD only).
More detials refer to Issue https://github.com/redhat-developer/service-binding-operator/issues/385
Handle errors in `olm.listCSVs()` and also check CSV resources before add watching.
The fake client will not return 404 error while listing non-existing resources kind. So test case is not present for this error handling. Maybe we could add cases in e2e test.
=> Handle errors for CSV CRD does not installed

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/binding_test.go, pkg/controller/servicebindingrequest/planner.go, pkg/controller/servicebindingrequest/reconciler_test.go, test/mocks/fake.go
fixes #408 
When `applicationSelector` was missing from SBR, the `status` field would not get updated. This PR fixes this issue.
Sample SBR:
```
metadata:
namespace: sbo-try-1
spec:
backingServiceSelectors:
- resourceRef: db-demo
kind: Database
```
=> Status should be updated when application selector is missing

pkg/controller/servicebindingrequest/retriever.go
According to https://github.com/redhat-developer/service-binding-operator/issues/415, the duplication is a bug.
=> remove duplicated env when read secret

pkg/controller/servicebindingrequest/binding.go, pkg/controller/servicebindingrequest/binding_test.go
If a sbr is created with a bad customEnvVar template, the sbr cannot be deleted. Issue https://github.com/redhat-developer/service-binding-operator/issues/429
Check the SBR's `DeletionTimestamp` before calling `Retriever.Get()` as the data is not used in deletion path.
Unit test cases added
=> check SBR deletion before calling retriever.Get()

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go
fix #419 
Prerequisites- have an imported app and a database CR
Create a sbr 
```
metadata:
namespace: service-binding-demo
spec:
resourceRef: nodejs-rest-http-crud-git
group: apps
version: v1
resource: deployments
kind: Database
resourceRef: db-demo
```
Now delete the imported app.
Now delete the sbr instance
`oc delete sbr binding-request -n=service-binding-demo`
The sbr will get deleted and will not error out on the unavailability of the deleted app
=> Delete the sbr even when application has been previously deleted 

pkg/controller/servicebindingrequest/sbrcontroller.go
Bug introduced in PR https://github.com/redhat-developer/service-binding-operator/pull/397.
Should check CSVs using resource `clusterserviceversions` instead of kind `ClusterServiceVersion`
=> fix csv resource checking

pkg/controller/servicebindingrequest/binding_test.go, pkg/controller/servicebindingrequest/planner.go
- Fixes generic binding bug
- Refer -> https://github.com/redhat-developer/service-binding-operator/pull/414/files#r407707455
- Reverts some changes introduced in this PR ->  https://github.com/redhat-developer/service-binding-operator/pull/414
1. Follow the steps given in this [example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to:
- install DB operator, Service Binding Operator
- Import an application
- Create a DB instance 
2. Create the following `ServiceBindingRequest`:
```
metadata:
namespace: service-binding-demo
spec:
kind: Database
resourceRef: db-demo
```
3. Use …
=> fixes generic binding

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/binding.go, pkg/controller/servicebindingrequest/planner.go, pkg/controller/servicebindingrequest/related_resources.go, pkg/controller/servicebindingrequest/retrieve_decoupled.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go
According to issue https://github.com/redhat-developer/service-binding-operator/issues/387, an envVarPrefix will be added to backingServiceSelector to support multiple service binding as below shows:
```
backingServiceSelectors:
- group: groupname
kind: Binding
resourceRef: resourceName
envVarPrefix: testprefix
```
Add a field envVarPrefix.
=> Add an envVarPrefix field to backingServiceSelector

pkg/controller/servicebindingrequest/reconciler.go
The ApplocationNotFound is not propagated to the reconciler as an error. Remove redundant checking
=> Remove redundant checking

Makefile
Generated CSV does not contain the following fields:
* categories
* description
* icon
and they are required for publishing the operator to community hub. Hence, we are adding them manually.
Use 0.0.23 CSV version as template when generating a new one. `service-binding-operator.v0.0.23.clusterserviceversion.yaml` contains a curated set of fields like proper description, maintainer list, icon, etc.
```
make push-to-manifest-repo
```
The generated manifest can be submitted to community-operator project without manual editing.
=> use 0.0.23 CSV version as template when generating a new one

examples/commons.mk, examples/java_postgresql_customvar/README.md, examples/knative_postgresql_customvar/README.md, examples/nodejs_awsrds_varprefix/README.md, examples/nodejs_ibmcloud_operator/README.md, examples/nodejs_postgresql/README.md, hack/examples-commons.sh
Currently, the examples use the version of the SBO installed from `community-operators`. I was not easy to try those examples with the latest version of the examples that are built from `master`.
Providing means to run those examples with the latest `master` version of SBO also supports automated tests that implement the example's scenarios.
This is a dependency for #441.
This PR adds make target for installing the latest SBO version from `master` using a custom `OperatorSource` and renames the current make targets (for the community version) by adding `community` suffix.
Tests introduced in #441 use this update.
=> Add a choice of installing SBO either from community or master in examples

pkg/controller/servicebindingrequest/annotations.go, pkg/controller/servicebindingrequest/annotations_test.go, pkg/controller/servicebindingrequest/binding.go
Part of https://github.com/redhat-developer/service-binding-operator/pull/442 as requested by @isutton  
Seperate `SetSBRAnnotations`/`RemoveSBRAnnotations` functions.
After this change `SetSBRAnnotations`/`RemoveSBRAnnotations` is only used to modify the object without updating it using clientset. The original behaviour is changed to `SetAndUpdateSBRAnnotations`/`RemoveAndUpdateSBRAnnotations`.
This is helpful for functions which want to combine set/remove SBRAnnotations with other modifications as a single updating request.
Test cases included.
=> Separate SetSBRAnnotations/RemoveSBRAnnotations functions

Makefile, hack/validate-release.sh
The current version comparison is against the value in the master branch. This is not the version that is published.  The published version is available in the community operator repo.
Compare version number against the version in the community operator repo.
To run the validation script:
```
export KUBECONFIG=</path/to/kubeconfig>
make validate-release
```
=> Validate version number against version in the community operator repo

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
This cleanup is required to autogenerate CRD from the source.
Refer:
https://github.com/redhat-developer/service-binding-operator/pull/469#discussion_r425122945
Remove unnecessary comment
Regular tests should pass.
=> Remove unnecessary comment

vendor/modules.txt
[1] Fixes issue #483 which is about failure to run operator locally through CLI `make local`.
[1] Adds `vendor/modules.txt` file auto-generated by `go mod vendor`.
[1] CLI `make local` should be success and operator should run locally.
=> fixes `make local` CLI

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/controller.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/servicebinder.go, pkg/controller/servicebindingrequest/servicebinder_test.go, pkg/testutils/testutils.go, test/mocks/fake.go
Discussion https://github.com/redhat-developer/service-binding-operator/issues/450
Mixed using of clientsets will cause trouble for testing. As dynamic client is enough for binder to  interact with the API server, it is better to use a single dynamic client.
- Remove dependency of client.Client in binder.
- Change the search behavior of binder for cases that `ResourceRef` is defined expilictly. Fake client will not filter objects by fieldselector.
- Add RESTMapper to binder to convert GVK and GVR
Fixed potential test issues.
=> Use dynamic client to interact with the API server

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go
Updates ServiceBindingRequestStatus.Applications documentation comment to:
[1] remove the word `ApplicationObjects`
[2] specify the `name` filter criteria of applications
=> Updates ServiceBindingRequestStatus.Applications documentation comment

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/controller.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/sbrcontroller.go, pkg/controller/servicebindingrequest/sbrcontroller_test.go
Fix issue https://github.com/redhat-developer/service-binding-operator/issues/422
Besically align https://github.com/redhat-developer/service-binding-operator/issues/422#issuecomment-619260714 Except:
Instead of hard-coded watching typical workloads at starting, this change will add watching for GVKs defined in application selector at runtime. As for typical workloads with status as subresources,  the existing predicate function which checks the`metadata.generation` is able to avoid noises.
Also split `Set/Remove SBRAnnotations` function into two seperate functions. It is useful to combine the updating for application CR. 
Unit tests added and manual testing passed.
=> Add watching for workloads

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, pkg/controller/servicebindingrequest/service.go, pkg/controller/servicebindingrequest/servicecontext.go
With the configuration values collection and aggregation solved in #407, this change introduces the `id` field in backing service selectors to be used as alias while composing custom environment variables.
Solves #396 
#407 has grouped service configuration values in the template context using the following the version, api group, kind and name (for example `{{ .v1alpha1.postgresql_baiju_dev.Database.db_testing.status.dbConnection }}`).
This change groups service configuration values in the template context using the optional `id` field declared by the user, allowing the user to write `{{ .db_testing.status.dbConnection }}` instead.
=> Introduce id field in service selector to be used as shortcut in custom environment variables

cmd/manager/main.go
Per issue https://github.com/redhat-developer/service-binding-operator/issues/488 
Make changes per 
https://github.com/operator-framework/operator-sdk/blob/c93321571d8300bb1f60f548de12e83f05d2d267/doc/user-guide.md#leader-for-life
https://github.com/operator-framework/operator-sdk/blob/c93321571d8300bb1f60f548de12e83f05d2d267/doc/user-guide.md#leader-with-lease
No change in deployment yaml , so by default the `leader-for-life` will be used. 
`leader-with-lease` is enabled only when the environment variable SERVICE_BINDING_OPERATOR_LEADER_ELECTION_OPTION is set to `leader-with-lease` explicitly 
There is no main_test.go ..  So I didn't add test case for this yet. 
=> make leader-with-lease as an option of deployment

pkg/controller/servicebindingrequest/service.go, pkg/controller/servicebindingrequest/servicecontext_test.go
Fixes: #477 
currently secret is being added copy by reference of `&item` var, which is being changed after each for loop iteration,
so eventually resource slice will have same address elements. 
```
for _, item := range lst.Items {
if owner.UID == uid {
resources = append(resources, &item)
}
}
```
This is being changed in PR where addresses passed to slice would be different.
```
for idx, _ := range lst.Items {
if owner.UID == uid {
resources = append(resources, &lst.Items[idx])
}
}
```
Run all tests with `make test-unit`
=> [Fix #447]  correctly detect multiple secret created by a service operator

Makefile
it looks like that recently codecov bash script we pull from https://codecov.io/bash got updated,
breaking 'upload-codecov-report' make rule. The token we use is read from
`/usr/local/redhat-developer-service-binding-operator-codecov-token/token`
and that file is mounted from a read-only volume. The codecov script tries to write something on that volume and it fails.
In order to fix the issue, we read token uuid within Makefile and pass it to the codecov script
=> fixed CI unit jobs

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/secret.go, pkg/controller/servicebindingrequest/secret_test.go, pkg/controller/servicebindingrequest/servicebinder.go
#512 
https://issues.redhat.com/browse/APPSVC-610
[1] Sets `ownerReference` to secret, so that after SBR deletion, secret can be deleted by garbage collector.
[1] OwnerReference information is added to intermediate secret.
[1] Follow the steps [here](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to create application, DB and SBR successfully.
[2] Delete SBR:
```
➜ oc delete sbr binding-request
```
[3] Check the presence of secret `binding-request`
```
➜ oc get secret binding-request               
Error from server (NotFound): secrets "binding-request" not found
```
The secret `binding-request` should be deleted successfully.
[1] We already have a e2e test to test successful deletion of secret after SBR is deleted -> …
=> Add owner reference to secret

Makefile
The current test namespace name is generated  - e.g. `test-namespace-72500cf4-96a3-4670-89a9-028eb8728307` - which is 52 characters long.
That long namespace names currently cause problems when exposing routes to applications' services (such as `nodejs-rest-http-crud`) (https://github.com/openshift/oc/issues/486).
This PR shorten's the generated part to the first 8 characters of the UUID (e.g. `test-namespace-72500cf4`) to make the namespaces' name reasonable long (24 characters).
`make test-e2e`
=> Make test namespace shorter to avoid having invalid - too long - URLs

pkg/controller/servicebindingrequest/reconciler_test.go
We support binding multiple backing services to a single application, this test is to vouch for that feature.
Adding a new test `TestBindTwoSbrsWithSingleApplication` in reconciler_test.go.
To run all the unit tests
`make test-unit`
To run only this test
`go test ./pkg/controller/servicebindingrequest/ -run=TestBindTwoSbrsWithSingleApplication -v`
=> Add unit test to verify binding two ServiceBindingRequests with a single application

README.md
Tiny bracket change for proper .md rendering
=> Proper render for the route_k8s_link in the readme.md

deploy/olm-catalog/README.md
The link to the operator-framework olm-catalog doc is broken.
=> The framework's olm-catalog doc now resides at a new place

test/e2e/servicebindingrequest_test.go
As described in https://github.com/redhat-developer/service-binding-operator/issues/549#issuecomment-657500353 by @isutton:
>Currently when the application is created after the SBR, even if the GVK of the application is being observed (corev1.Deployment for example), there is no way to correlate the application resource and the SBR to be reconciled since there are no annotations in the application resource yet (the annotation is created after the first reconciliation).
In other words the scenarios where the Application is created after the SBR are currently not supported by the SBO and the tests that implement those passes or fails randomly by cheer chance.
e2e scenarios where the application is created after SBR are disabled to un-block all the other PR that are blocked by those e2e …
=> Temporarily disable e2e scenarios not supported by SBO.

Makefile
Latest yamllint==1.24.0 was released a few hours ago and it appears to be broken. 
An issue on yamllint: https://github.com/adrienverge/yamllint/issues/285
Our lint job in CI is failing with the same reason.
=> Use yamllint==1.23.0

pkg/controller/servicebindingrequest/annotations/configmap_test.go, pkg/controller/servicebindingrequest/annotations/errors.go, pkg/controller/servicebindingrequest/annotations/resource.go, pkg/controller/servicebindingrequest/annotations/secret_test.go, pkg/controller/servicebindingrequest/envvars/envvars.go, pkg/controller/servicebindingrequest/nested/accumulator/accumulator.go, pkg/controller/servicebindingrequest/nested/path.go
After #407 an undocumented behavior regarding annotations meant to extract
config map and secret values has been unwillingly changed and needs to be
reverted.
The annotations handling mechanism after #407 extracts the whole contents of
the config map or secret to the same path where the config map or secret name
has been stored (resulting in, for example, .status.secretName.password if
.data.password is present in the associated resource) to workaround
situations where two services might have a password field within different
paths and might get shadowed, whereas before #407 it used to extract the
contents to the root of the resulting object (for example, .password),
imposing no issue whatsoever because there were only one service being
declared in the binding.
Closes #485 
This change …
=> Revert annotation handling mechanism to not use the original config map or secret resource name location

Makefile, pkg/controller/servicebindingrequest/annotations/annotations.go, pkg/controller/servicebindingrequest/annotations/resource.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/retriever_test.go, pkg/controller/servicebindingrequest/service.go, pkg/controller/servicebindingrequest/service_test.go, pkg/controller/servicebindingrequest/servicecontext.go, pkg/controller/servicebindingrequest/servicecontext_test.go, test/e2e/servicebindingrequest_test.go, test/mocks/fake.go, test/mocks/mocks.go, test/third-party-crds/postgresql_v1alpha1_database_crd.yaml
A bug has been introduced in #407, changing the existing behavior where the data collected from the resource indicated by the annotation (either a `corev1.ConfigMap` or `corev1.Secret`) should also replace the field indicating the resource name with the collected data.
Let's take a look in the following example resource:
```yaml
metadata:
annotations:
servicebindingoperator.redhat.io/status.secretName: binding:env:object:secret
status:
secretName: the-secret
```
Before #407, when `status.secretName` was used in a custom environment variable template, it would contain the whole `data` section of the related Secret, as the following excerpt from #475:
```
"status": {
"secretName": {
"apikey": "XXXX",
"iam_apikey_description": "Auto-generated for key 0aef56aa-fbb2-4dd7-8bc7-972302e14573", …
```
=> Fix bug where binding data is expected to overwrite the related resource name

pkg/controller/servicebindingrequest/annotations.go, pkg/controller/servicebindingrequest/annotations_test.go, pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/sbrcontroller.go, pkg/controller/servicebindingrequest/secret.go, pkg/controller/servicebindingrequest/secret_test.go, test/mocks/fake.go, test/mocks/mocks.go
To resolve issue #509 
Initially the resourceVersion of the secret used to get updated even without any change in the data field. In this refactor we would only update the secret after fetching the already existing secret and comparing it's data with the payload(new data to be injected). If secret exists then we go further to check the contents with which the secret needs to be updated. If data is same we skip the update, if data is diff we go further with updating the secret resource.
`make test-unit`
Import an app
create a db
create a sbr
Check the reosurceVersion of the secret and the in the envVar of the deployment. Both should be the same. 
Update the backing service, now the intermediate secret reourceVersion should change and further change envVar in the deployment
For further more …
=> Fix infinite reconcile loop

.gitignore, Makefile, hack/check-python/check-PEP8-style.sh, hack/check-python/check-python-docstyle.sh, hack/check-python/detect-common-errors.sh, hack/check-python/detect-dead-code.sh, hack/check-python/measure-cyclomatic-complexity.sh, hack/check-python/measure-maintainability-index.sh, hack/check-python/prepare-env.sh
Currently, there are multiple python's virtual environment directories
* `./out/venv3`
* `./venv`
used throughout the repository:
* `make setup-venv`
* `make lint-yaml`
* `make lint-python-code`
* `make test-acceptnace`
* `make validate-release`
* `make prepare-bundle-to-quay`
* `make push-bundle-to-quay`
This PR unifies them all under a single one under `out/venv3`:
Any or all of the above make targets.
=> [acceptance-tests] Unify python's venv.

hack/deploy-sbo-local.sh
`killall`is not installed in the `test` container by default. So, calling it as part of the acceptance tests setup breaks it (along with per-PR checks). However, there is no need for running `killall` before local SBO is started in CI, since there are no `operator-sdk` or `service-binding-operator-local` processes running in the `test` container, anyway.
Removed `killall` line in the `deploy-sbo-local.sh` script.
`make test-acceptnace-setup`
=> [acceptance-tests] Remove killall line before starting local SBO

Makefile
Currently the only output is the console which is useful for humans but not for processing my a machine. xUnit format is a standardized format and the acceptance tests should generate this form in order to be able to report those results in an automated way later on.
This PR enables the generation of the results in [xUnit](https://en.wikipedia.org/wiki/XUnit) format. The result files are stored under the `out/acceptance-tests` directory.
* `make test-acceptance`
* look under `out/acceptance-tests` for `*.xml` files
=> [acceptance-tests] Generate test results in JUnit XML/xUnit format.

.gitignore
acceptance tests create some Kubernetes object-related cache inside `.kube`. So adding it `.gitignore`
=> Add .kube cache dir to .gitignore

Makefile
Makefile target better fits as a non-PHONY target.
Use file path as target
Run `make generate-openapi` and check for the existence of binary.
=> Use file path as target

hack/deploy-sbo-local.sh
Follow-op on #574 
There is indeed no need to kill the `operator-sdk` or `service-binding-operator-local` processes in the CI, since it all runs in a clean container. However, it is necessary for the development of the acceptance tests or for running those locally to kill those processes every time a local SBO instance is started for the acceptance tests to avoid conflicts and to make sure the acceptance tests are executed with the latest codebase.
A kill all mechanism is introduced into the `./hack/deploy-sbo-local.sh` which covers both cases of `killall` tool being installed or not.
`make test-acceptance-setup`
=> [acceptance-tests] Kill local sbo process before running acceptance tests.

Makefile
Remove consistent-crds-manifests-upstream as it is no longer required since manifests-upstream has been removed.
```
consistent-crds-manifests-upstream:  Copy crd from deploy/crds to manifests-upstream/
merge-to-master-release  -- Target for merge to master dev release --
merge-to-master-release:  Make a dev release on every merge to master
push-to-manifest-repo  -- Target for pushing manifest bundle to service-binding-operator-manifest repo --
push-to-manifest-repo:  Push manifest bundle to service-binding-operator-manifest repo
prepare-bundle-to-quay  -- Target for preparing manifest bundle to quay application --
prepare-bundle-to-quay:  Prepare manifest bundle to quay application
push-bundle-to-quay   -- Target to push bundle to quay
push-bundle-to-quay:  Push manifest bundle to quay …
```
=> Remove an unused target and Makefile cleanup

Makefile, hack/deploy-sbo-local.sh
Currently the only archived data is the test console output archived in CI. To be able to investigate any acceptance tests failures it is useful and necessary to gather as much data as possible and archive it along the prow job that executed it.
This PR:
* Moves the local SBO log under `out/acceptance-tests` directory
* Adds `test-acceptance-artifacts` target (so it can be called in the CI as soon as the tests are finished) to copy the whole `out/acceptnace-tests` directory to the `/tmp/artifacts` (which is the directory from CI ultimately gathers and archives the artifacts)
This is a dependency for https://github.com/openshift/release/pull/10489
`make test-acceptance-artifacts`
=> [acceptance-tests] Enable test artifacts gathering in CI

Makefile
Currently, some of the acceptance test setup related targets are directly at `test-acceptnace` which makes the `test-acceptance-setup` target not usabe standalone for the first time (or in CI). By moving those as part of the `test-acceptance-setup` make sense and also make it possible to use the `test-acceptance-setup` target standalone to run local SBO instance without the need of invoking the `test-acceptance`.
This PR:
* Moves setup-related dependencies of `test-acceptance` target to` test-acceptance-setup` one
* Fixes `error: unable to recognize "deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml": no matches for kind "ServiceBindingRequest" in version "apps.openshift.io/v1alpha1"` occurence in the CI logs.
`make test-acceptance-setup`
=> [acceptance-tests] Move setup-related dependencies to test-acceptance-setup

test/acceptance/features/steps/dboperator.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py
`OperatorSource` is [deprecated](https://docs.openshift.com/container-platform/4.4/release_notes/ocp-4-4-release-notes.html#ocp-4-4-marketplace-apis-deprecated) for OpenShift 4.4+
Fixes [APPSVC-592](https://issues.redhat.com/browse/APPSVC-592) for the acceptance tests.
Use of `OperatorSource` to install PostgreSQL DB operator is replaced by the use of plain `CatalogSource`.
=> [acceptance-tests] Replace deprecated OperatorSource by CatalogSource.

pkg/controller/servicebindingrequest/annotations/attribute.go, pkg/controller/servicebindingrequest/annotations/bindinginfo.go, pkg/controller/servicebindingrequest/annotations/bindinginfo_test.go, pkg/controller/servicebindingrequest/annotations/configmap_test.go, pkg/controller/servicebindingrequest/annotations/resource.go, pkg/controller/servicebindingrequest/annotations/secret_test.go, pkg/controller/servicebindingrequest/nested/path.go
This PR is to fix the issue we reported in https://github.com/redhat-developer/service-binding-operator/issues/475#issuecomment-646114247.
@isutton 
Could you take a look at this PR? It need to be rebased after your PR https://github.com/redhat-developer/service-binding-operator/pull/515 is merged.
=> make custom_env_var can reference the whole secret/configmap without using a slash

hack/check-python/detect-dead-code.sh
Currently the dead code detection part of python linters `make lint-python-code` do not find the `*.py` files and is useless.
This PR fixes the dead code detection script (`hack/check-python/detect-dead-code.sh`) to include all the `*.py` files
`make lint-python-code`
=> [acceptance-tests] Fix python linting - dead code detection

pkg/controller/servicebindingrequest/service.go, pkg/controller/servicebindingrequest/servicecontext.go, pkg/controller/servicebindingrequest/servicecontext_test.go
Fix for #584 
Do not error out when resource not found in the binding resources, Instead log it as stated below
```
2020-07-23T21:04:33.309+0530	DEBUG	reconciler.buildServiceContexts	Resource not found in Bindable Resources	{"Request.Namespace": "try", "Request.Name": "binding-request-etcd", "ServiceBindingRequest.Name": "binding-request-etcd", "Error": "the server could not find the requested resource"}
```
=> Reconcile should log error if a resource is not found in detect Bindable resource

pkg/controller/servicebindingrequest/mapper.go, pkg/controller/servicebindingrequest/mapper_test.go, pkg/controller/servicebindingrequest/sbrcontroller.go, pkg/controller/servicebindingrequest/servicebinder.go, test/e2e/servicebindingrequest_test.go, test/mocks/etcd_operator_mocks.go, test/mocks/mocks.go
This PR deprecates the usage of annotations to relate Service Binding Requests and its services and applications in favor of a programmatic lookup.
Closes #458 
The main reason for this change is to reduce the amount of writes in the API server during the SBR reconciliation: those writes can trigger other reconciliation processes leading to unexpected race conditions; additionally, those annotations also seem to not be necessary to find a direct relationship between a Service Binding Request and a related resource, being it a service, application or the intermediate secret as changes in this PR can show.
This PR does not stamp the SBR information to related resources using annotations during the reconciliation process, and performs a lookup up to identify the SBR associated with an …
=> Deprecate relationship annotations

README.md
Since our goal has evolved to support binding to non-operator-backed services too, I'm updating the README
Example of binding to non-operator-backed service:
https://github.com/redhat-developer/service-binding-operator/blob/master/examples/route_k8s_resource/README.md
=> Update README.md to reflect our goal

README.md
The readme didn't quite reflect that backing services needn't be operator-backed services necessarily.
Follow-up to https://github.com/redhat-developer/service-binding-operator/commit/d371e191360a26b6d0df6c80f78c8d0835b1a9f4 .
I will make a separate PR to update https://github.com/redhat-developer/service-binding-operator/blob/master/docs/OperatorBestPractices.md
=> docs: Backing service needn't be provided by operators only

hack/deploy-sbo-local.sh, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py
Currently, the time to reach the required condition in cases below is exceeded sometimes. In that case the test fails even if the condition is met eventually.  Those relatively small timeouts make the acceptnace tests flaky.
This PR increases the timeout for:
* "Get SBR info by jsonpath" to 10 minutes (was 25s)
* "Get SBR info by jq" to 10 minutes (was 25s)
* "Start local SBO instance" to 120s (was 60s)
* "Wait for the Node.js app to re-deploy" to 2 minutes (was 60s)
`make test-acceptnace`
=> [acceptance-tests] Increase various timeouts to make acceptance tests less flaky

examples/java_postgresql_customvar/README.md, examples/java_postgresql_customvar/service-binding-request.yaml
https://issues.redhat.com/browse/APPSVC-482
This PR updates the existing [java_postgresql_customenvvar example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/java_postgresql_customvar) with additional information  to demonstrate use of annotations to fetch data from different data structures.
The example demonstrates that it is not required for the developer to create distinct annotations for sibling properties.
If the postgresql database CR has `tag` field:
```
tags:
- "centos7-12.3"
- 123
``` 
with sibling properties of different data structure type:
-  `string` _centos7-12.3_
-  `int` _123_ 
Then
this Custom Environment Variable in the Service Binding Request
```
- name: TAGS 
value: '{{ .postgresDB.spec.tags }}' 
```
will result in creation of …
=> Updates  java-postgresql example to demonstrate use of annotations to fetch data from scalar, sequence, map data structures

test/acceptance/features/steps/command.py, test/acceptance/features/steps/steps.py
Currently the acceptance tests assume `KUBECONFIG` and `PATH` variables are set. If any of them is not set, the tests fails with the failure similar to the following:
```
Given Namespace [TEST_NAMESPACE] is used                                                                                                                                      # test/acceptance/features/steps/steps.py:33 0.001s
Traceback (most recent call last):
File "/home/user/go/src/github.com/redhat-developer/service-binding-operator/out/venv3/lib64/python3.7/site-packages/behave/model.py", line 1329, in run
match.run(runner.context)
File "/home/user/go/src/github.com/redhat-developer/service-binding-operator/out/venv3/lib64/python3.7/site-packages/behave/matchers.py", line 98, in run
self.func(context, *args, …
```
=> [acceptance-tests] Fix negative corner cases handling env variables

README.md
Link to mailing list info page will users to join and see old archives.
Add link
Preview the README using https://pypi.org/project/grip/ and see if the link is available.
=> Add link to mailing list info page

test/acceptance/features/steps/quarkus_application.py, test/acceptance/features/steps/steps.py
Currently the `"{app_name}" deployment must contain SBR name "{sbr_name1}" and "{sbr_name2}" step assumes that the output from the `oc get ... -o jsonpath=...` would be in the form of a go structure:
`[map[secretRef:map[name:{binding-request-1}]] map[secretRef:map[name:{binding-request-2}]]]`
which is what the `oc` v4.5 produces. However when `oc` v4.6 is used, the output changes into a valid JSON su:
`[{{"secretRef":{{"name":"{binding-request-1}"}}}},{{"secretRef":{{"name":"{binding-request-2}"}}}}]`
So if one runs the acceptance tests with `oc` v4.6, the scenarios fails on that step, because the expected and actual values of the result do not match even if the operator's behavior is correct.
This PR:
* Adds a support for both variants of the result in the `"{app_name}" deployment must …
=> [acceptance-tests] Fix multiservice step to work with both oc v4.5 and v4.6

README.md
Resolve https://github.com/redhat-developer/service-binding-operator/issues/658
=> Add link to SBO channel in Kubernetes slack workspace

Makefile
This is the first step of removing the `e2e` test suite in favour of `acceptance` tests (https://issues.redhat.com/browse/APPSVC-648)
This PR disables the `e2e` tests by default unless `ENABLE_OBSOLETE_E2E` is set to `true`.
A warning like the following is shown instead:
```
$ make test-e2e
!WARNING: e2e tests are obsolete and will be removed soon in favour of acceptance tests,
!          so they are disabled by default. If you need to run it anyway, set ENABLE_OBSOLETE_E2E=true in the environment.
make: Nothing to be done for 'test-e2e'.
```
`make test-e2e`
=> Mark e2e testsuite obsolete and disable it before removal.

test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindKnativeService.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature
The acceptance tests sometimes fail for a timing issue caused by checking the desired binding outcome (such as `envFrom` in the deployment) - that was supposed to be done by the binding. Such checks sometimes happen before the actual binding process is finished.
Anything about the outcome should be checked only after the binding is finished, which is ensured by verifying the `.status.condition[]` steps after the SBR is applied.
This PR moves the steps to verify desired binding outcome after the SBR status conditions are verified. After those steps passed, there is ~100% certainty that the desired binding outcome is in place so the tests can validate it.
=> [acceptance-tests] Check SBR status after the SBR step before checking the desired binding outcome

Makefile, hack/deploy-clean.sh, hack/e2e-cleanup.sh, hack/remove-sbr-finalizers.sh
Currently the acceptance tests setup deletes the test namespace and creates a new one. But if there are finalizers set on SBRs in that test namespace (for whatever reason) the deletion of the namespace is stuck in Terminating state.
Like in https://github.com/redhat-developer/service-binding-operator/issues/476
This PR removes all the finalizers from all the SBRs in the test namespace just before it attempts the namespace deletion.
`make e2e-cleanup`
=> Remove SBR finalizers in the test namespace before deleting the namespace

pkg/controller/servicebindingrequest/sbrcontroller.go, pkg/controller/servicebindingrequest/sbrcontroller_test.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py, test/acceptance/resources/backend.operator.manifest.yaml
Fix #508 
Follow steps mentioned here https://github.com/redhat-developer/service-binding-operator/issues/508#issuecomment-646777684
to test the functionality
Steps to reproduce:
Install the Strimzi Operator (v0.18.0).
Install the Service Binding Operator./ Run the SBO locally
Create ServiceBindingRequest, application, and the backing service (Kafka) resources:
```
metadata:
name: kafka-producer-binding
spec:
resourceRef: nginx-deployment
group: apps
version: v1
resource: deployments
backingServiceSelectors:
- group: kafka.strimzi.io
kind: Kafka
resourceRef: my-cluster
version: v1beta1
id: kaf
customEnvVar:
- name: BOOTSTRAP_SERVERS
value: |-
{{- range .kaf.status.listeners -}}
{{- if and (eq .type …
```
=> Trigger reconcile on updates to services' status

Makefile
Currently the only hard-coded tag expression is `~@disabled`, but there is no way to pass any additional tags or expressions without actual editing the `Makefile`.
This PR introduces a way to pass additional tag expression to enable running specific acceptance test scenarios/features per tags.
`TEST_ACCEPTANCE_TAGS=@negative make test-acceptance` to run just the negative scenarios.
or
1) Add e.g. `@wip` tag to a single scenario in any `*.feature` file:
```
Feature: ...
@wip
Scenario: ...
...
```
2) Run `TEST_ACCEPTANCE_TAGS=@wip make test-acceptnace` to run only the tagged scenario.
=> [acceptnace-tests] Enable running specific features or scenarios by tag expression

examples/nodejs_etcd_operator/README.md
etcd cluster instance unable to run with this in openshift-operators namespace:
`apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
name: "etcd-cluster-example"
spec:
size: 3
version: "3.2.13"`
Use this to make it run on openshift-operators namespace
`apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
annotations:
etcd.database.coreos.com/scope: clusterwide
name: etcd-cluster-example
namespace: test-namespace-881f5a0b
spec:
repository: quay.io/coreos/etcd
size: 3
version: 3.2.13
`
=> update etcd example README

pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/acceptance/features/bindAppToService.feature
Fix #486 
Steps to confirm
- Create a postgres db
```
apiVersion: postgresql.baiju.dev/v1alpha1
kind: Database
metadata:
name: db-demo
spec:
image: docker.io/postgres
imageName: postgres
dbName: db-demo
```
- Create a SBR
```
metadata:
spec:
kind: Database
resourceRef: db-demo
id: postgresDB
envVarPrefix: HELLO
customEnvVar:
- name: JDBC_URL
value: 'jdbc:postgresql://{{ .postgresDB.status.dbConnectionIP }}:{{ .postgresDB.status.dbConnectionPort }}/{{ .postgresDB.status.dbName }}'
- name: DB_USER
value: '{{ .postgresDB.status.dbCredentials.user }}'
- name: DB_PASSWORD
value: '{{ .postgresDB.status.dbCredentials.password }}'
- name: …
```
=> Remove global & service prefixes from customEnvVar

hack/check-python/prepare-env.sh, hack/check-python/requirements.txt, test/acceptance/features/requirements.txt
Recently the python linter started to require `flake8_polyfill` module which is not installed. 
This PR adds `flake8_polyfill` module into the installed dependencies.
`make lint-python-code`
=> [acceptance-tests] Fix python linting dependencies.

Makefile, test/acceptance/features/steps/servicebindingoperator.py
Fixes: [APPSVC-692](https://issues.redhat.com/browse/APPSVC-692)
Currently the only way how the acceptance tests can test the SBO is by using the local instance of the operator (that is built and started as a local binary as part of the test setup). It would be useful if we could start the SBO instance independently (by installing it into OpenShift cluster via OperatorHub, by running the local instance independently of the acceptance testing process, by running SBO in a local or remote container...).
* `TEST_ACCEPTANCE_START_SBO` variable has an additional option for `remote` which means that the SBO instance is already running outside the scope of the acceptnace testing process and no local instance is started.
* The step for checking if the SBO is running is updated to take this option …
=> [acceptance-tests] Make it possible to run SBO instance independendly on acceptnace testing setup.

test/acceptance/features/bindAppToService.feature
Refer https://issues.redhat.com/browse/APPSVC-677
To cover this, the Service Binding Request without application selector scenario from the bindAppToService.feature has been updated by adding steps to check that the intermediate secret was created and that it contains the expected data.
Testing-
Run `make test-acceptance`
=> Check intermediate secret data contents in case of no application

test/acceptance/features/requirements.txt, test/acceptance/features/steps/knative_serving.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/quarkus_application.py, test/acceptance/features/steps/serverless_operator.py
Currently the knative-related acceptance tests scenarios fails for timeout sometimes.
This PR:
* Increases various timeouts around quarkus app steps
* Changes the way to detect knative app is imported - uses number of replicas on deployment instead of checking `Available` status condition
* Changes the way to detect that serverless operator is running but checking for CSV and then for all the expected pods from it's deployments given by the CSV.
=> [acceptance-tests] Fix timeout waiting for serverless/knative to be imported

Makefile, hack/check-feature-files.sh
Currently it is very easy to accidently commit and merge acceptance test tags placed in the `*.feature` files which shouldn't be allowed.
This PR makes it harder to merge `*.feature` files that contains so-called "forbiden" tags (currently they are`@wip` and `@dev`) by:
* Introducing `lint-feature-files` Makefile targed that goes through all the `*.feature` files under  `test/acceptance/features` directory and looking for forbidden tags and failing when and of the forbidden tag is found.
* Including the `lint-feature-files` targed among the main `lint` used by the per-PR checks.
`make lint` or
`make lint-feature-files`
=> [acceptance-tests] Add checks for feature files among linters.

Makefile, test/acceptance/features/bindAppToService.feature
Resolves: [APPSVC-710](https://issues.redhat.com/browse/APPSVC-710)
Currently there is no out-of-the-box way to run just a few tests to just check fundamental pieces of acceptance scenarios.
The only way now is to manually mark a chosen scenario with a tag and than run the acceptance tests with `TEST_ACCEPTANCE_TAGS=@<tag>` variable set, which is repetitive and annoying and has a potential for including those forgotten tags into a codebase.
This PR:
* Introduces `test-acceptance-smoke` Makefile target that executes a sub-set of acceptance scenarios marked with `@smoke` tag.
* Tags `Bind an imported Node.js application to PostgreSQL database in the following order: Application, DB and Service Binding` scenarios with `@smoke` tag to be part of the smoke testing sub-set.
`make …
=> [acceptance-tests] Introduce way to smoke test with acceptance tests

README.md
`OperatorSource` API has been removed from OpenShift 4.6 nightly.
=> remove OperatorSource reference from readme

Makefile, test/acceptance/features/environment.py, test/acceptance/features/steps/servicebindingoperator.py, test/acceptance/features/steps/steps.py
Currently there are some resources (such as CRD, role, role-binding,...) that are installed for acceptance tests before the actual tests are execued. This should only by the case when SBO is running `local`. In case SBO is running `remote`ly (i.e. installed in OpenShift beforehand) all of the resources should be already there by the installation.
This PR:
* Skips steps in Makefile that install resources
* Introduces `SBO_NAMESPACE` variable to specify in which namespace the remote SBO is running. 
1. Install SBO via OperatorHub (`beta` channel)
2. Run  `TEST_ACCEPTANCE_START_SBO=remote SBO_NAMESPACE=openshift-operators make test-acceptance-smoke
`
=> [acceptance-tests] Do not install any resource if SBO is remote.

hack/remove-sbr-finalizers.sh
Jira: [APPSVC-726](https://issues.redhat.com/browse/APPSVC-726)
Currently the `hack/remove-sbr-finalizers.sh` script uses hardcoded short names for Service Binding resources `sbr`/`sbrs` that is not reliable - it fails sometimes to find the resource by that short name. And also it can change in the future.
This PR changes the script to use exact name of the CRD instead of the short name.
`make test-cleanup`
=> Use CRD name instead of hard-coded "sbr" or "sbrs" in hack/remove-sbr-finalizers.sh

test/acceptance/features/requirements.txt, test/acceptance/features/steps/dboperator.py, test/acceptance/features/steps/servicebindingoperator.py, test/acceptance/features/steps/steps.py
Jira: [APPSVC-724](https://issues.redhat.com/browse/APPSVC-724)
Currently the assertion in acceptance tests is done by a combination of `pyshould` library and Python's `assert` statements. which is confusing.
This PR:
* Replaces use of `pyshould` library in acceptance tests is replaced by assert statements with concrete error messages to explain what went wrong or unexpected
* Removes `pyshould` from requirements
=> [acceptance-tests] Replace pyshould by asserts and refine error messages

Makefile
﻿This fixes the build of this operator on other architectures.
The Makefile used to build the binary no longer hardcodes GOARCH=amd64.
make test-unit passes on both ppc64le and s390x.
=> Do not hardcode GOOS/GOARCH

pkg/controller/servicebinding/sbrcontroller.go, pkg/controller/servicebinding/sbrcontroller_test.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/steps.py
Refer https://issues.redhat.com/browse/APPSVC-709
As an extension to https://github.com/redhat-developer/service-binding-operator/pull/597 the new changes can now trigger reconcile on changes to services' metadata.Annotations
Run
Test - `make test-acceptance`
=> Trigger reconcile on updates to services' metadata.Annotations specific to service bindings

Makefile
Path was broken recently
fix path
```
export GO_PACKAGE_ORG_NAME=redhat-developer
make generate-openapi
```
=> Fix path for openapi-gen

test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/steps.py
We support binding service to application present in a different namespace. This PR adds an acceptance test to validate it.
https://issues.redhat.com/browse/APPSVC-418
`make test-acceptance VERBOSE=3`
=> Add acceptance test to validate cross-namespace service support

test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceAnnotations.feature
Currently the acceptance tests do not cover use of element type `sliceOfMaps`. 
This PR:
* Adds acceptance test scenario for annotation with `elementType=sliceOfMaps`
* Extract all annotations specific scenarios into a separated `bindAppToServiesAnnotations.feature` file to keep number of lines at bay.
```
make test-acceptance VERBOSE=3
```
=> [acceptance-tests] Add acceptance test for CRD annotations with sliceOfMaps

examples/java_postgresql_customvar/README.md, pkg/controller/servicebinding/binding/definition.go, pkg/controller/servicebinding/binding/definition_test.go, pkg/controller/servicebinding/binding/model.go, pkg/controller/servicebinding/binding/spec_test.go, pkg/controller/servicebinding/envvars/envvars.go, pkg/controller/servicebinding/envvars/envvars_test.go, pkg/controller/servicebinding/nested/nested.go, test/acceptance/features/bindAppToServiceAnnotations.feature
Implements:
* https://github.com/k8s-service-bindings/spec/issues/131
* [APPSVC-739](https://issues.redhat.com/browse/APPSVC-739)
Fixes:
* https://github.com/redhat-developer/service-binding-operator/issues/728
* [APPSVC-729](https://issues.redhat.com/browse/APPSVC-729)
The `unsupported type` error is thrown because when using a list of strings (a.k.a. slice of strings) the env variable building piece of SBO does not recognize it because it ends up as `[]string` which is not the case of `[]interface{}` or any other considered case.
This PR:
* Adds a case for `[]string` in a similar way as `[]interface{}` is in the env variable build part of SBO.
* Improves a bit of error logs related to the issue.
* Implements case for `sliceOfStrings` without `sourceValue`
* Adds acceptance tests
`make …
=> Fix annotations with sliceOfStrings

test/acceptance/features/environment.py
Jira issue: [APPSVC-651](https://issues.redhat.com/browse/APPSVC-651)
The acceptance tests require oc v4.5+ and that needs to be checked and fail fast if not satisfied.
This PR:
* Ensures that `oc` version used for acceptance tests is 4.5+ as required by checking the version in `before_all` function and failing the suite fast in case the version is not satisfied.
`make test-acceptance-smoke`
=> [acceptance-test] Check oc version is 4.5+

test/acceptance/features/environment.py
When using `TEST_ACCEPTANCE_START_SBO=remote` option, `SBO_NAMESPACE` is required to be set to a non-empty value, as well. Currently the check for that is missing so when the acceptance tests are executed without `SBO_NAMESPACE` the tests attempt to run with empty name for SBO namespace which is invalid.
This PR:
* Enhances the check for `SBO_NAMESPACE` env variable value in `before_all` hook.
* Fixes: https://issues.redhat.com/browse/APPSVC-744
Running `TEST_ACCEPTANCE_TESTS=remote make test-acceptance` should correctly fail with:
```
HOOK-ERROR in before_all: AssertionError: SBO_NAMESPACE is required but it is not set or it is empty: 
```
=> [acceptance-tests] Fix remote SBO namespace checking.

pkg/controller/servicebinding/reconciler.go, pkg/controller/servicebinding/reconciler_test.go, pkg/controller/servicebinding/servicebinder.go, pkg/controller/servicebinding/servicebinder_test.go, test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingConfigMap.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/bindKnativeService.feature, test/acceptance/features/customEnvVar.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature, test/mocks/fake.go, test/mocks/mocks.go
According to the discussion in https://github.com/redhat-developer/service-binding-operator/issues/665, we need to add a overall Ready condition to show what is the status of the ServiceBinding CR.
=> Create an overall `Ready` to indicate whether the SBR reconcile is completed successfully #665

openshift-ci/Dockerfile.tools
This is a dependency for the acceptance tests to be able to run in containerized environment.
The tool needs to be added and merged in a separated PR prior merging the actual PR that depends on it, because of how OpenShift CI and Prow works.
This PR add `podman` package to the `root` base image for OpenShift CI jobs
=> Add podman package to OpenShift CI's base image.

test/acceptance/features/bindAppToServiceAnnotations.feature
PR #681 introduced Ready condition but some of the acceptance tests were
extended wrongly, i.e. they are not checking Ready condition on SB created
within the test
Steps are modified so that the proper SB.Ready is checked.
=> Check ready status of SB created in acceptance test

Makefile, hack/deploy-sbo-local.sh, hack/stop-sbo-local.sh
Currently the `deploy-sbo-local.sh` and `make local` use `operator-sdk run --local` to start the local instance of SBO (SDK builds and run the `build/_output/bin/service-binding-operator-local`, however the "production" binary that is part of the shipped image is build by the `make build` target and is actually `out/operator`:
This means that the acceptance tests actually test a different binary, than the one that is a part of releases.
This PR:
* Modifies the `local` Makefile target to build and use `out/operator` binary
* Modifies the `test-acceptance-setup` Makefile target to build and use `out/operator` binary
* Updates the `hack/deploy-sbo-local.sh` script to be able to start local instance of SBO either in background or foreground.
* Unifies the above targets to all use …
=> [acceptance-tests] Use out/operator binary for local SBO instance instead of operator-sdk

Makefile, hack/allure-report.sh, test/acceptance/Dockerfile.allure, test/acceptance/README.md, test/acceptance/entrypoint.sh
Currently there is effectively no docs nor tutorials available for the acceptance tests.
This PR adds a description and tutorials for the acceptance tests.
Read and follow the instructions [`./tests/acceptance/README.md`](https://github.com/pmacik/service-binding-operator/blob/acceptance-tests-readme/test/acceptance/README.md)
=> [acceptance-tests] Update README.md with description and tutorial for acceptance tests

Makefile
Recent merge of https://github.com/redhat-developer/service-binding-operator/pull/677/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R459 accidentally replaced `Docker` in name of `Dockerfile.rhel`
This PR reverts that replacement to original file name.
=> Fix (revert) accidental replacement of word Docker in Makefile.

test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingConfigMap.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/bindKnativeService.feature, test/acceptance/features/customEnvVar.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature, test/acceptance/features/steps/steps.py
Currently in a lot of acceptance testing  scenarios 3 steps together are used to verify that the service binding has finished and is ready with by checking the particular status conditions like the following:
```feature
Then jq ".status.conditions[] | select(.type=="CollectionReady").status" of Service Binding "{name}" should be changed to "True"
And jq ".status.conditions[] | select(.type=="InjectionReady").status" of Service Binding "{name}" should be changed to "True"
And jq ".status.conditions[] | select(.type=="Ready").status" of Service Binding "{name}" should be changed to "True"
```
All the scenarios that have those steps share a common pattern that only differs with the name of the Service Binding resource.
This can be simplified in a single step such as `Service Binding "{name}" …
=> [acceptance-tests] Merge steps for 'all-is-ready' into a single simplified step

pkg/apis/operators/v1alpha1/doc.go
Fix https://github.com/redhat-developer/service-binding-operator/pull/735#discussion_r515024936
=> Update generated group name from apps.openshift.io to operators.coreos.com

README.md, install.sh
Adding installation steps for running SBO on minikube or any other vanilla k8s.
Fix for https://github.com/redhat-developer/service-binding-operator/issues/536
=> Add installation steps for SBO with OLM on vanilla k8s

test/acceptance/features/bindAppToService.feature
Currently the negative scenarios for checking that SB is not updated after an attempt to apply an invalid SB have the 2 steps:
* `Service Binding is applied` (with valid CR YAML - pre-update)
* `Invalid Service Binding is applied` (with invalid CR YAML - attempt to update CR)
The steps' impementation uses value of `.metadata.resourceVersion` to verify  that the SB was NOT updated. The problem is in case of fast enough client side and/or slow enough server side that can lead to a situation where the `invalid SB is applied` step happens quickly while the effect of the previous steps is still in progress (so the original (pre-update) SB's `resourceVersion` is still undergoing changes) and therefore the validation (and the scenario) fails.
This PR:
* Removes the flakiness of negative …
=> [acceptance-tests] Fix flakiness of negative scenarios for verifying SB is not updated in cases of invalid attempts to update

.travis.yml
* The change opens up the possibility to add additional jobs that will be triggered on PR submission.
* The actual image publishing from master has been moved into stage "Push dev image to Quay"
* The job gets executed only if changes are pushed or merged to `master` branch
=> Restructure Travis CI conf to allow additional jobs in future

README.md
This PR introduces curl based single line command for install.sh so that users don’t need to clone the repo.
=> Install SBO by curling the install script

.travis.yml
By default Travis cancel the job if no new output is produced within 10 minutes. Some of our acceptance test steps can be slower on some infrastructures/VMs. Hence, let's increase the timeout to prevent premature job cancellation.
=> Increase Travis waiting to 30mins

.travis.yml, Makefile
Currently there is no direct way to produce SBO bundle and index images.
Jira issue: [APPSVC-766](https://issues.redhat.com/browse/APPSVC-766)
This PR:
* Adds Makefile targets for building such operator bundle index image that can be used in `CatalogSources`.
* Adds `release-operator` Makefile target to run all the necessary steps to do a release to quay such as building operator, operator bundle and bundle index, and pushing it to quay.
* Adds that release target into Travis job that builds operator bundle for each merge-to-master, so that an index image is build for each merge to master, too.
* Replaces versioning scheme from `<operator_version>-<commit_count>` to `<operator_version>-<commit_short_sha>`
* Replaces operator image ref in CSV to use `@sha256:...` digest instead of tag.
1. …
=> Automate building of SBO bundle index images usable in CatalogSources on each merge to master

Makefile
Only files ending with `.yaml` or `.yml` should be considered.
Fix regex.
Run `make lint`
=> Improve regex to find yaml files

test/acceptance/features/steps/generic_testapp.py
The issue was detected in https://travis-ci.org/github/redhat-developer/service-binding-operator/builds/747368812
polling call in `GenericTestApp.get_file_value()` ignores now `ConnectionError`
and keeps trying to retrieve the file until reaching the given timeout.
=> Step "Content of file in application pod" does not fail in case of connection errors

.travis.yml, hack/start-minikube.sh, install.sh
Such approach is much closer to reality and can catch various packaging and installation issues.
`install.sh` script got updated to support:
* Installing an arbitrary index image, configurable via `OPERATOR_INDEX_IMAGE` env var
* Installing from an arbitrary channel, configurable via `OPERATOR_CHANNEL` env var
* container runtime can be specified via `CONTAINER_RUNTIME` env var (default: docker)
* installed OLM version is now 0.17.0
* Registries authentication can be skipped by setting `SKIP_REGISTRY_LOGIN` env var
* Non interactive registry logins are supported via setting `OPERATOR_REGISTRY_USERNAME` and `OPERATOR_REGISTRY_PASSWORD` env vars
* Location of Docker `config.json` file can be customized through `DOCKER_CFG` env var. In combination with
non-interactive logins, the script can …
=> run acceptance tests on Travis against the operator installed in the cluster

Makefile, hack/prepare-operatorhub-pr.sh
The target extracts files from published bundle image (default: for the current HEAD commit)
and place them into `out/operatorhub-pr-files/service-binding-operator` folder so that they
could be easily copied into local clone of `github.com/operator-framework/community-operators`,
creating PR afterwards.
The added target makes the operator publishing to the upstream easier:
* Use already bundles published from master, no need to build any images
* The existing bundles are already verified, i.e. acceptance tests passed on
them
* The bundles refer images using shas, so the published upstream operator
has already support for air-gapped installations
=> Add `prepare-operatorhub-pr` target

Makefile
When reading short sha using `git rev-parse --short`, the default length might be different on various machines.
Since short commit id used in many places in the release process, we need to fix to a known size to avoid surprises.
[This Travis job](https://travis-ci.org/github/redhat-developer/service-binding-operator/builds/748306646#L272) shows for example that `GIT_COMMIT_ID` was of size 7, but on my machine its size is 8.
=> Makefile GIT_COMMIT_ID length set to 8

test/acceptance/features/steps/steps.py
Currently in `Knative serving is running` step the `knative-serving` namespace is being created no matter what. That can cause errors and failures in case the namespace already exist.
This PR updates the step above to create the `knative-serving` namespace only if it does not already exist.
`TEST_ACCEPTANCE_TAGS="@knative" make test-acceptance`
=> [acceptance tests] Create knative-serving namespace only if it does not exist

.travis.yml
With `prepare-operatorhub-pr` target, we do not need to push and keep bundle data in the separate repo on each merge to master.
=> Stop pushing bundle metadata to additional manifest repo

.travis.yml, Dockerfile.rhel, go.mod, openshift-ci/Dockerfile.tools
Upgrade go version from 1.14 to 1.15 .
New golang version now also available in https://github.com/openshift/release/tree/master/projects/origin-release/golang-1.15
fixes #657
=> Upgrade go version from 1.14 to 1.15

test/acceptance/features/steps/etcdoperator.py, test/acceptance/features/steps/steps.py
Currently `etcd` related tests installs etcd operator from `community-operators` catalog source. Recently etcd was removed from that catalog source which caues constant failures of the etcd-related acceptance tests. However, etcd operator is available in `operatorhub.io`.
This PR:
* Fixes failing acceptance tests in CI by changing catalog source for etcd operator for acceptance tests to be `operatorhub.io`
=> [acceptance-tests] Change catalog source for etcd operator to operatorhub.io

Dockerfile.rhel
Due to recently introduced image pull limits, we see occasionally job failures at Travis.
Hence, openshift/origin-release:golang-1.15 image got mirrored to quay
and that image is now our base build image.
=> Fix Docker image pull limits 

.codecov.yaml, .travis.yml, Makefile
Currently codecov.io reports are not being uploaded for unit tests due to a typo in shell script to read from `CODECOV_TOKEN_PATH` that leads to the following complain:
```sh
/bin/bash: ODECOV_TOKEN_PATH: No such file or directory
```
This PR:
* Fixes the `upload-codecov-report` Makefile target to properly use variable `CODECOV_TOKEN_PATH` to pass the token file.
* Adds a Travis CI merge-to-master job to upload codecov report for master commits to be used as baselines for PRs
`4.6-unit` PR check tests it
=> Fix reading codecov.io token from CODECOV_TOKEN_PATH.

pkg/controller/servicebinding/binding/definition.go, pkg/controller/servicebinding/binding/definition_test.go
`outputName` is not honoured in `mapFromDataFieldDefinition` implementation.
Closes #817.
make test-unit
Thanks !
=> Take into account outputName in mapFromDataFieldDefinition (#817)

Makefile, install.sh
Currently in `install.sh` script SBO's package name in subscription is hard-coded to be `service-binding-operator`. However there are situations where the name of the package is different - such is the case of Red Hat's productized version of SBO, where the package name is actually `rh-service-binding-operator`. So currently the installation fails because of the package name mismatch. 
This PR:
* Introduces an optional parameter (`OPERATOR_PACKAGE` env variable) that can be used to specify the desired name of the package. The default value remains `service-binding-operator`.
* Run tests with OpenShift and Red Hat oficial bundle:
```sh
OPERATOR_INDEX_IMAGE_REF=registry.redhat.io/redhat/redhat-operator-index:v4.6 OPERATOR_CHANNEL=preview CSV_PACKAGE_NAME=rh-service-binding-operator make …
```
=> Make operator package name configurable in install.sh

pkg/apis/operators/v1alpha1/register.go, pkg/apis/operators/v1alpha1/servicebinding_types.go, pkg/controller/servicebinding/common.go, pkg/controller/servicebinding/reconciler.go, pkg/controller/servicebinding/reconciler_test.go, pkg/controller/servicebinding/sbrcontroller.go, pkg/controller/servicebinding/servicebinder.go, pkg/controller/servicebinding/servicebinder_test.go
API consumer would like to bring a minimal set of transitive dependencies in his project,
when adding service binding API as one of the dependencies. Thus, following constants
need to be moved our of controller/servicebinding to api/operators/v1alpha package:
* GroupVersionKind of ServiceBinding
* several condition types
Fizes #375
=> Move user-relevant constant to API package

README.md, docs/User_Guide.md
Motivation:
Broken links in SBO User Guide
Rename SBO User Guide.md to SBO_User_Guide.md
Fix #823
=> Remove unwanted broken links and fix annotations in the SBO User Guide

Makefile, hack/get-test-namespace
This fixes regression introduced in PR #848 - we should reuse created test namespace
across multiple runs of acceptance tests
Two consecutive runs of `make test-acceptance` should create just single
test namespace.
=> Fix regression: previously create test namespace is used across test runs

controllers/reconciler.go, test/acceptance/features/unbindAppToService.feature
I will add the UT and acceptance tests later
=> Fix ServiceBinding removal when service not exist

.gitignore, README.md, api/v1alpha1/servicebinding_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/operators.coreos.com_servicebindings.yaml, controllers/reconciler.go, controllers/retriever.go, controllers/retriever_test.go, controllers/service.go, controllers/service_test.go, controllers/servicebinder.go, controllers/servicecontext.go, controllers/servicecontext_test.go, docs/User_Guide.md, examples/pod_spec_path/README.md, examples/route_k8s_resource/README.md, pkg/envvars/envvars.go, pkg/envvars/envvars_test.go, pkg/naming/naming.go, pkg/naming/naming_test.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindWithCustomNamingStrategies.feature, test/acceptance/features/deleteBackendServiceAndRecreate.feature, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature
At the moment, binding names declared through annotations or CSV descriptors are processed before injected into the application according to the following strategy:
- names are upper-cased
- service resource kind is upper-cased and prepended to the name
Currently there is no way to build custom environment variable key except using naming prefix, This PR provides a way to have go template in the service field of SB request which can then be used to prepare environment variable name.
With this PR we can define `namingStrategy`, a template which can be used in the preparation for env variable key.
sample SB request would look like
```
apiVersion: operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
name: binding-example
spec:
namingStrategy: '{{ .service.kind | lower …
```
=> Add implementation to support flexible naming strategies to prepare binding names

Makefile, hack/remove-sbr-finalizers.sh
Recent [update to a new version of `operator-sdk`](https://github.com/redhat-developer/service-binding-operator/pull/848]) changed the way how the manifests (e.g. CRD) are generated and removed the `deploy/crd/*crd.yaml` file that was used in the `test-cleanup` script so now the script fails complaining that it could not find the file.
This PR:
* Changes the location from which the SBO's CRD is taken for the `test-cleanup`  script to the one that is generated by the `manifests` target. 
`make test-cleanup`
=> Fix test-cleanup to use the generated CRD

docs/User_Guide.md
Few places in the user guide still refer to the old naming convention
This PR renames `applicationSelector` to `application` and `backingServiceSelectors` to `services` in the User_Guide.md
=> Fix: replace in user guide backingServiceSelectors/applicationSelector appearances with services/application

.github/actions/setup-cli/action.yaml, .github/actions/setup-cli/setup_tools.sh, .github/workflows/pr-checks.yaml, Makefile, hack/check-python/requirements.txt, hack/prepare-operatorhub-pr.sh, hack/release-manifest.py, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingConfigMap.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/bindWithCustomNamingStrategies.feature, test/acceptance/features/customEnvVar.feature, test/acceptance/features/deleteBackendServiceAndRecreate.feature, test/acceptance/features/examples.feature, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/unbindAppToService.feature
Fixes - https://github.com/redhat-developer/service-binding-operator/issues/799
https://issues.redhat.com/browse/APPSVC-769
The release manifest file can be created by running the make target `release-manifests` . On running the make release-manifests target a release.yaml file is produced in the /out dir. This release.yaml can now be used to install the SBO on a vanilla k8s.
A GitHub action job name `acceptance_without_olm` is configured to test the release manifest file on a vanilla k8s cluster.
=> Generating release.yaml

Makefile, config/manager/kustomization.yaml, config/manifests/kustomization.yaml, config/rbac/kustomization.yaml
* Several roles were bound to a wrong service account, fixed to use `service-binding-operator`
* we are not protecting /metric endpoints for now, hence the auth proxy roles are removed from the bundle
* service binding viewer and editor clusterroles added to the bundle so that cluster roles can make use of them
and enable appropriate users/service-accounts to manage service bindings
=> Consolidate roles landing into bundle

Makefile
Currently, the `stop-local` target contains invalid references to the hack scripts that make the target fail.
This PR fixes paths to hack scripts for `stop-local` target.
`make stop-local`
=> Fix stop-local hack dir path.

Makefile
This PR adds the `make clean` target back which deletes the temp directory OUTPUT_DIR, which was deleted by the PR https://github.com/redhat-developer/service-binding-operator/pull/848/files
=> Add clean target for removing temp dirs

hack/remove-sbr-finalizers.sh
Recent merge of the PR https://github.com/redhat-developer/service-binding-operator/pull/865 introduced a change to the api group which was not reflected in the `./hack/remove-sbr-finalizers.sh` script called by the `test-cleanup` target and fails complaining that `error: the path "config/crd/bases/operators.coreos.com*.yaml" does not exist` since than.
This PR fixes the path for CRD from above.
`make test-cleanup`
=> Fix path to CRD in repo used by test-cleanup

.github/workflows/pr-checks.yaml
Currently the `Acceptance tests running on Kubernetes without using OLM` GHA job runs the acceptance tests in a local mode (The default mode determined by the `TEST_ACCEPTANCE_START_SBO` variable (with the locally started instance of SBO) while it builds operator's images and than installs SBO into the Kubernetes, at the same time. The acceptnace tests should be run in a remote mode to use that instance, that is being installed into Kubernetes.
This PR:
* Switches the non-OLM acceptance testing GitHub Action to remote mode by setting `TEST_ACCEPTANCE_START_SBO` variable to `remote`.
* Removes useless `OPERATOR_VERSION` variable
This PR's GitHub Action check: `Acceptance tests running on Kubernetes without using OLM`
=> Fix non-OLM acceptance tests use SBO installed in Kubernetes, not local instance

.github/workflows/pr-checks.yaml
Currently the acceptance tests results in GitHub Actions are not being published or tracked - only overall PASS or FAIL. That makes it very tedious to investigate what went wrong if the tests fail.
This PR:
* Adds steps to acceptance testing GHA jobs to collect and publish the results into Testspace where it can be easily looked and browsed.
Check `testspace/analytics` PR check
=> Attach acceptance tests report in GH Actions

.github/workflows/pr-checks.yaml
The logs are copied into `sbo.log` file and packed together with other build artifacts
=> Collect the operator logs after running PR test jobs

install.sh
Currently, `install.sh` script produces unused file named `1` as a result of an output redirect.
This PR:
* Removes the redirect in  `install.sh` script to file named `1` to keep the output visible.
After running `./install.sh` check the root directory for the presence of a file name `1` it should not be there.
=> Remove output redirect in install.sh to file named 1 

test/acceptance/README.md
Curently the acceptance test documentation is a bit old and do not reflect the latest features of the framework
This PR:
* Updates the acceptance test framework documentation
Follow [`test/acceptance/README.md`](https://github.com/pmacik/service-binding-operator/blob/acceptance-tests-readme/test/acceptance/README.md).
=> [acceptance-tests] Update acceptance testing docs.

Makefile, hack/check-conflicts.sh
Currently it is possible to accidently commit conflict notes (such as `<<<<<<< HEAD`) in source files without actually noticing it.
This PR:
* Adds a new linter for detecting git conflict notes in tracked and staged files.
`make lint-conflicts`
=> Add check for the presence of conflict into linters

pkg/reconcile/pipeline/handler/project/impl.go, pkg/reconcile/pipeline/handler/project/impl_test.go, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/steps.py, test/acceptance/features/unbindAppToService.feature
When projecting bindings as files, we inject volume and volume mount carrying the same name
as binding resource, but when binding is removed, we wrongly look to remove volume and volume mount
having the name equal to the binding secret.
This change fixes it and introduces the missing acceptance tests.
Fixes #948
=> Fix: Remove volume and volumemount from app resource when unbinding

pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, pkg/reconcile/pipeline/handler/mapping/impl_test.go, test/acceptance/features/bindAppToMultipleServices.feature
service structs are initialized inside a `for range` loop, and the loop variable is passed as a reference to each of service structs.
However, with each new iteration its value changes, but the reference remains the same, leading that the value of the last iteration
is passed to all service structs eventually.
* do not pass loop variable to service structs
* unit tests were extended to detect regressions in the future
* `Bind two backend services by creating 1 SBR to a single application` acceptance test was modified to detect regressions in the future
Fixes #944
=> Regression fix: refer multiple services in custom mapping templates

test/acceptance/features/steps/steps.py, test/acceptance/features/unbindAppToService.feature
Currently the accepatce tests for unbinding are only checking that the injected binding information is removed from application when SB is removed. However a secret is created for SB and that secret should be removed as well and those tests are missing that check.
This PR adds checks for removal of intermediate secret when SB is removed
=> [acceptance-tests] Add checks for removal of intermediate secret when SB is removed

controllers/servicebinding_controller.go, pkg/reconcile/pipeline/handler/project/impl.go, pkg/reconcile/pipeline/handler/project/impl_test.go, test/acceptance/features/steps/steps.py, test/acceptance/features/unbindAppToService.feature
* added missing acceptance tests
* in the reconcile loop, add finalizer only if deletion timestamp is unset
* unbind handler: stop processing and do not retry in case of any error when reading the application resource
=> Check if unready binding can be removed

.github/actions/setup-podman/registries_template.conf, .github/workflows/merge-to-master.yaml
Recently merged https://github.com/redhat-developer/service-binding-operator/pull/972 introduced a conflict in the local registry set up for building the PR images and the base image used to build SBO operator image.
This PR
* Fixes the conflict by setting a registry mirror
* Re-uses the setup-cli action introduced in the above mentioned merged PR in merge-to-master jobs
PR checks will do.
=> Fix SBO base image conflict with local registry in GH Actions

pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, test/acceptance/features/bindMultipleAppsToSingleService.feature, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/openshift.py
- Fix `.spec.application.name` field becoming mandatory
- If more than one application is selected through label selectors, all will be considered for binding
Fixes #965
=> Fix support for label selectors

pkg/reconcile/pipeline/context/service.go, pkg/reconcile/pipeline/context/service_test.go
We were bitten by https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
Fixed the loop to use the new variable.
Fixes #966
=> Fix Service.OwnedResources() to return correct result

pkg/reconcile/pipeline/api.go, pkg/reconcile/pipeline/builder/pipeline.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, pkg/reconcile/pipeline/context/service_test.go, pkg/reconcile/pipeline/handler/collect/impl.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, pkg/reconcile/pipeline/mocks/mocks_pipeline.go, pkg/reconcile/pipeline/secretbackedbindings.go, pkg/reconcile/pipeline/secretbackedbindings_test.go, pkg/util/util.go.go, test/acceptance/features/bindAppToServiceUsingSecret.feature
Application can be bound to a provisioned service:
https://github.com/k8s-service-bindings/spec#provisioned-service
* collect.ProvisionedService handler detects if referred service contains a reference to secret containing the bindings
* unit and acceptance tests demonstrate the contact and exposed functionality
Fixes #548
=> Add provisioned service support

.github/actions/collect-kube-resources/action.yaml, .github/workflows/pr-checks.yaml
Currently, only SBO logs are collected for debugging.
This PR:
* Adds steps to acceptance testing PR checks to collect additional resources such as Subscription, CatalogSource, Pods and Deployments related to SBO for debugging purposes
PR checks will do.
=> [acceptance-tests] Collect kube resources as well as SBO logs in GH workflows

pkg/binding/annotationmapper.go, pkg/binding/annotationmapper_test.go, pkg/binding/definition.go, pkg/binding/definition_test.go, pkg/binding/jsonpath.go, pkg/binding/jsonpath_test.go, pkg/binding/mocks/mocks.go, pkg/binding/model.go, pkg/binding/spec.go, pkg/binding/spec_test.go, pkg/reconcile/pipeline/builder/pipeline_integration_test.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature
Calls to `unstructured.NestedFieldCopy` replaced by usage of [JSONPath) parser from client-go library](https://github.com/kubernetes/client-go/tree/master/util/jsonpath).
Refactored `model` and builders to keep jsonpath in original form, without spliting into steps
* This simplified the annotation parsing logic
* Since we now support full JSON path, we cannot now detect selected field name in all possible cases.
Hence using "service.binding" annotation key alone is allowed only when `objectType` is set to `Secret` or `ConfigMap`
In all other cases, "service.binding/xxx" convention must be used. A number of unit tests adjusted accordingly
* reenabled the acceptance tests that requires `path` to be a regular JSONPath expression
(the provided expression uses subscript operator to locate the …
=> Support for selection of array element in paths

hack/check-python/measure-cyclomatic-complexity.sh, hack/check-python/measure-maintainability-index.sh
Currently, the python linters `measure-cyclomatic-complexity.sh` and `measure-maintainability-index.sh` miss the directories of the acceptance tests where most of the python code is and only test python files under `hack` directory.
This PR includes acceptance test directories containing python code to be tested by `measure-cyclomatic-complexity.sh` and `measure-maintainability-index.sh` python related linters.
`make lint-python-code`
=> Include missed directories for python linters

config/rbac/kustomization.yaml, config/rbac/servicebinding_controller_role.yaml, config/rbac/servicebinding_controller_rolebinding.yaml, test/acceptance/features/pluggableRBAC.feature, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/servicebindingoperator.py, test/acceptance/features/steps/steps.py
https://github.com/redhat-developer/service-binding-operator/issues/900
* Added Aggregated cluster role for the operator to get access to the resources
* Added rolebindings for the openshift-operators and operators namespace
For testing this we need to 
* re-create the bundle manifests
* Deploy the operator and bundle to the cluster
=> Add rbac support for spec alignment

apis/binding/v1alpha1/servicebinding_types.go, apis/binding/v1alpha1/servicebinding_webhook.go, apis/binding/v1alpha1/servicebinding_webhook_test.go, apis/common.go, apis/spec/v1alpha2/servicebinding_types.go, apis/spec/v1alpha2/servicebinding_webhook.go, apis/spec/v1alpha2/servicebinding_webhook_test.go, test/acceptance/features/immutableBindings.feature
Webhooks modifed to prevent updates only if `.spec` part of the binding is updated
Fixes #996
=> Allow metadata updates on Ready bindings

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Currently the generated CSV in bundle manifests misses the `displayName` and `description` in owned CRDs sections of `.spec.customresourcedefinitions` for `v1alpha2` version:
```yaml
spec:
apiservicedefinitions: {}
customresourcedefinitions:
owned:
- description: ServiceBinding expresses intent to bind an operator-backed service with an application workload.
displayName: Service Binding
kind: ServiceBinding
name: servicebindings.binding.operators.coreos.com
- kind: ServiceBinding
name: servicebindings.service.binding
version: v1alpha2
```
That leads to the following display of "Name Not Available" and "No description available" in [OperatorHub.io's page](https://operatorhub.io/operator/service-binding-operator):
This PR adds the meta-data for `v1alpha2` CRDs into …
=> Add v1alpha2 CRD meta-data into CSV

config/rbac/role.yaml, config/rbac/servicebinding_controller_rolebinding.yaml, controllers/binding/servicebinding_controller.go, controllers/common.go, controllers/spec/servicebinding_controller.go, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/resources/backend_crd.yaml, test/acceptance/resources/backends_bar.operator.manifest.yaml, test/acceptance/resources/backends_foo.operator.manifest.yaml, test/acceptance/resources/custom_app.operator.manifest.yaml, test/acceptance/resources/provisioned_backend.operator.manifest.yaml, test/acceptance/resources/provisioned_backend_with_annotations.operator.manifest.yaml
Signed-off-by: Bamacharan Kundu <bamachrn@gmail.com>
https://github.com/redhat-developer/service-binding-operator/issues/454
We have updated default access for service_binding controllers.
* For Binding resources, operator has all the access to read update delete and patch
* For Apps group access is to read and list
* for secretes access is to read update and create
* for pods read and update
=> Adjusted access for resources and apiversions 

apis/binding/v1alpha1/servicebinding_types.go, config/crd/bases/binding.operators.coreos.com_servicebindings.yaml, config/manager/kustomization.yaml
As someone learning both kubernetes and service binding operator, it helps to be able to read the API documentation that `kubectl explain` returns.  However, current documentation can be unclear in some contexts, leading to some confusion over intended behavior.  This aims to resolve some of the clarity issues and improve the built-in API documentation.
Summary of changes:
- Expand acronyms for the sake of clarity
- Use a descriptive mood when possible
- Address and rewrite some difficult-to-understand statements
I'm hoping to make this clearer -- let me know if there is anything incorrect about the changes I made (again, I'm new to this project, and I may have gotten something wrong).
No tests were needed for this change, as it's a documentation change.  Run `kubectl explain` on objects …
=> Improve documentation used by 'kubectl explain'

pkg/reconcile/pipeline/handler/collect/impl.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/resources/backend_crd.yaml
When using the `sliceOfMaps` elementType in a service binding annotation, the operator panics when the specified sourceValue does not exist in the underlying maps, although the expected behavior would be to inform the user the binding has an error through conditions.
This PR changes the current behavior by verifying that the extracted value is present, and reports an error in the service binding in the case that the sourceValue key isn't present.
Replaces #993 and fixes #967.
See #967 for reproducibility details.
=> Fix crash when service annotation with sliceOfMaps elements has invalid sourceValue

Makefile, config/manager/manager.yaml, config/manifests/bases/service-binding-operator.clusterserviceversion.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, config/webhook/service.yaml
* added annotation that indicates that the operator can be deployed in disconnected environments
* specified minimal supported kube version
* added containerImage annotation
* maturity set to 'candidate'
* explicit service account dropped from bundle
* common label renamed to service-binding-controller-manager
=> Apply CSV best practices

pkg/binding/annotationmapper.go, pkg/binding/annotationmapper_test.go, pkg/reconcile/pipeline/handler/collect/impl.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, test/acceptance/features/bindAppToServiceAnnotations.feature
If a service has an invalid service binding annotation set, we shouldn't attempt to bind the service.  However, current behavior catches most cases (such as an invalid path), but errors currently are ignored, and when either `elementType` or `objectType` isn't valid, we panic.  This could cause issues for users.
Rather than panicking, we should fail the binding request and report any errors that are thrown.
Attempting to bind against a service with an garbage annotation should now fail and report errors in the binding status.  For example, ```service.binding/credentials: path={.status.dbCredentials},elementType=asdf``` should fail.  This currently implements unit and acceptance tests for both `elementType` and `objectType` errors.  It also adds an acceptance test for invalid paths for the …
=> Treat invalid "elementType" and "objectType" annotations as errors, not panics

pkg/reconcile/pipeline/handler/project/impl.go, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/service_binding.py
Issue: #983 
This PR:
* Removes duplicate setting of `SERVICE_BINDING_ROOT` env variable
* Adds acceptance test related to `SERVICE_BINDING_ROOT` env variable for binding as files
Related acceptance tests in PR checks.
=> Remove duplicate setting of SERVICE_BINDING_ROOT env while projecting files

test/acceptance/openshift-setup.sh
Currently the non-admin user account  for acceptance tests is setup via `oc apply` command, which potentially ovewrites OAuth setup of the openshift cluster.
Running the `openshift-setup.sh` script multiple times might cause the `oc login` with the `acceptance-tests-dev` user to fail with:
```
Error from server (InternalError): Internal error occurred: unexpected response: 500
```
This PR:
* Changes the way the new IDP is configured in `OAuth` from using `oc apply` command to `oc patch` to avoid breaking cluster's other IDPs 
Run `test/acceptance-tests/openshift-setup.sh` multiple times. No login error should occur.
=> [acceptance-tests] Use patch instead of apply for IDP setup to avoid braking cluster's IDPs

apis/binding/v1alpha1/servicebinding_types.go, config/crd/bases/binding.operators.coreos.com_servicebindings.yaml, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, test/acceptance/features/bindAppToProvisionedService.feature
Until now, the binding name was set through `.metadata.name` of `ServiceBinding` resource,
and that name was used in constructing binding mount point, i.e. `<SERVICE_BINDING_ROOT>/<binding name>`
Since `.metadata.name` value must be unique within all `ServiceBinding` resources in a given namespace,
the introduction of `.spec.name` allows us to overwrite `.metadata.name` and have more predictable
mount points inside containers.
This work aligns `binding.operators.coreos.com/v1alpha1 API` even further to the spec API:
https://github.com/servicebinding/spec#resource-type-schema-1
=> Add optional `.spec.name` to ServiceBinding to `binding.operators.coreos.com/v1alpha1 API`

apis/binding/v1alpha1/servicebinding_types.go, apis/spec/v1alpha3/servicebinding_types.go, config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
Currently the `config/manifests/bases/service-binding-operator.clusterserviceversion.yaml` file is not updated for latest version of spec `ServiceBinding` and `BindableKinds` CRDs and so it is generated without `displayName` and `description`.
This is how it is shown in operatorhub.io
and this is how it looks like in OpenShift's OperatorHub
See that the `ServiceBinding` from spec API does not have the proper name displayed (should be `Service Binding (Spec API Tech Preview)`)
This PR:
* Adds `BindableKinds` CRD into base CSV
* Updates version of `servicebindings.servicebinding.io` to `v1alpha3` in base CSV
* Removes deprecated and unused `+operator-sdk:gen-csv:...` annotations from `servicebinding_types.go` in both `binding` and `spec` apis.
With this PR this is how it looks in OpenShift …
=> Fix CSV manifests to reflect v1alpha3 version of spec API and recent addition of BindableKinds CRD

apis/binding/v1alpha1/servicebinding_webhook.go, apis/webhooks/admission.go, main.go, test/_projects/api-client/.gitignore, test/_projects/api-client/go.mod, test/_projects/api-client/main.go, test/_projects/api-controller/.gitignore, test/_projects/api-controller/go.mod, test/_projects/api-controller/main.go, test/library_test.go
SBO uses currently controller-runtime 0.6.4 and there the admission webhook `Request` struct
uses v1beta1 API. Later controller-runtime versions use `v1` version, and this
turned to generate compile error when SBO is included as dependency in a project
using latest controller-runtime as well.
The root cause for the issue is that the admission webhook is part of `api` package,
and therefore needs to be complied even if not used in the project.
There is no reasons why the webhook code need to be a part of `api` package, and
the issue is fixed by moving it in separate `apis/webhooks` package.
Two new test projects are added so that we can catch regressions.
Fixes #1022
=> fix compile error when using SBO as library with newer controller-runtime

config/rbac/kustomization.yaml, config/rbac/opstree_redis_clusterrole.yaml, config/rbac/role.yaml, controllers/crd/crd_controller.go, hack/get-test-namespace, pkg/binding/annotationmapper.go, pkg/binding/annotationmapper_test.go, pkg/binding/definition.go, pkg/binding/definition_test.go, pkg/binding/model.go, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/redisoperator.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
Provisioned `redis.redis.opstreelabs.in/v1beta1`/`Redis` instances are bindable out of the box, exposing following binding data:
* type (always set to 'redis')
* host
* password
In order to expose `type`, support for binding constant has been added. Namely, if a service binding annotation value does not specify `path`,
then the annotation value is used as the binding value. With that it is possible to state something like this:
```
service.binding/type: redis
```
Unit and acceptance tests have been added to verify the introduced behavior.
Solves indirectly #843
=> Add support for Opstree Redis operator-backed services

config/rbac/crunchy_postgres_clusterrole.yaml, config/rbac/kustomization.yaml, controllers/crd/crd_controller.go, pkg/binding/definition.go, pkg/binding/definition_test.go, pkg/binding/jsonpath.go, pkg/binding/jsonpath_test.go, pkg/binding/model.go, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
In order to read binding data from the right secret, the value of `path` key of a service binding annotation
is treated as a template:
* multiple json paths can specified and the results of their evaluation are rendered in the final binding value
* the template can contain arbitrary additional strings that are rendered 'as-is' in the final binding value
Hence, it is possible to generate proper secret reference and read binding data from it. In the case of
CrunchyData Postgres Operator, this is the right annotations:
```
"service.binding": "path={.metadata.name}-pguser-{.metadata.name},objectType=Secret",
```
On top of that, `user` is exposed as `username` as well, and `dbname` and `database`, so that
more applications can find all the binding data they need.
=> Add support for CrunchyData Postgres operator

apis/binding/v1alpha1/servicebinding_webhook.go, apis/binding/v1alpha1/servicebinding_webhook_test.go, apis/spec/v1alpha3/servicebinding_webhook.go, apis/spec/v1alpha3/servicebinding_webhook_test.go, config/webhook/manifests.yaml, pkg/reconcile/pipeline/context/spec_binding_impl.go, test/acceptance/features/bindAppToService.feature
A name and selector MUST NOT be defined in the same application
reference
Fix #974
=> A name and selector MUST NOT be defined together

test/acceptance/features/environment.py, test/acceptance/features/requirements.txt
Currently, in acceptance tests, there is a check to verify that (when used) `oc` CLI has a minimal version of `4.5`. However, the way how this check is implemented treats the versions only as plain strings and compares it only alphanumerically which does not work in all cases.
That comparison fails for example in case the actual version of `oc` CLI is e.g. `4.10.0-0.nightly-2021-10-31-210828`. That failure fails all scenarios with:
```
...
Running acceptance tests
TEST_ACCEPTANCE_START_SBO=remote \
TEST_ACCEPTANCE_SBO_STARTED= \
TEST_NAMESPACE=test-ns-a449 \
/home/cloud-user/service-binding-operator/out/venv3/bin/behave --junit --junit-directory /home/cloud-user/service-binding-operator/out/acceptance-tests  --no-capture --no-capture-stderr --tags="~@disabled" --tags="~@examples" …
```
=> [acceptance-tests] Fix oc version compare in before_all hook

README.md
We should link to blog posts and articles that talk about and/or demonstrate SBO.
=> Add links to relevant articles/blog posts

test/acceptance/features/steps/generic_testapp.py
Running acceptance tests on non-Intel arches requires that our generic test app is multi-arch as well.
The generic test app image is built and pushed to the new quay location with:
```
pushd test/acceptance/resources/apps/sbo-generic-test-app/ \
&& podman build --manifest sbo-generic-test-app:today \
--platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x . \
&& podman manifest push sbo-generic-test-app:today \
quay.io/service-binding/generic-test-app:20211112 \
&& popd
```
and `GenericTestApp` is updated to use the new pullspec.
Run the tests with this applied.
=> Use mutil-arch generic test app image

test/acceptance/features/allowBindingWhenUserHasPermissions.feature, test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToProvisionedService.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingConfigMap.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/bindMultipleAppsToSingleService.feature, test/acceptance/features/bindWithCustomNamingStrategies.feature, test/acceptance/features/customEnvVar.feature, test/acceptance/features/immutableBindings.feature, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature, test/acceptance/features/steps/app.py, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/service_binding.py, test/acceptance/features/steps/steps.py, test/acceptance/features/steps/util.py, test/acceptance/features/unbindAppToService.feature
This helps ensure less implicit dependencies between various acceptance tests; this was done as a part of investigating test concurrency.
We want to reduce implicit dependencies between acceptance tests, since that will help make our tests repeatable and more consistent.
Acceptance tests should now be using `$scenario_id` (or names derived from it) in most places.
Run acceptance tests.
=> Use $scenario_id in acceptance tests when possible

hack/common.mk
When making changes to mocked interfaces, I'd like a way for our build system to automatically regenerate our mocks.
`mockgen` is now placed in `bin/`, so installing it globally is no longer required.
I don't have the new `gen-mocks` recipe as a dependency for running unit tests, since you're not likely going to need to run it very often.  Ideally, I'd have it as a dependency and have it run only when mocked interfaces have changed in some way, but I'm not sure how to teach `make` to do that kind of introspection.
Run `make gen-mocks`; mocks should be regenerated.
=> build: add recipe for generating mocks

pkg/reconcile/pipeline/context/service/service.go, pkg/reconcile/pipeline/context/service/service_test.go
Saving service crd (`s.crd`) when there was an error while retrieving it (`s.CrdReader(s.groupVersionResource)`) can lead to `nil` pointer problems.
This was causing problem for odo when it tried to use SBO as a library.
Return error and don't save crd to `s.crd`.
Added a test that covers this scenario.
=> Make sure to return nil value when there was an error

pkg/binding/registry/registry.go, test/acceptance/features/steps/cloudnativepostgresoperator.py, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/supportExistingOperatorBackedServices.feature, test/acceptance/resources/apps/sbo-generic-test-app/Dockerfile, test/acceptance/resources/apps/sbo-generic-test-app/README.md, test/acceptance/resources/apps/sbo-generic-test-app/conf/lighthttpd.conf, test/acceptance/resources/apps/sbo-generic-test-app/postgres-ready.sh
The appropriate database host name is stored in `.status.writeService` field, and it is NOT
equal to `Postgres` resource name.
Changes:
* servicebinding host annotation got updated
* added `provider` binding, the value is set to `enterprisedb`
* generic test application is extended with `/postgres-ready` endpoint that
returns `OK` if the connection to Postgres database can be established using the provided bindings
* New version of the test application got pushed to the registry for all supported arches
* Cloud Native Postgres acceptance test got update to assert the database connection
Fixes #1077
=> Fixed exposed host binding item for databases provisioned by Cloud Native Postgres Operator

pkg/binding/registry/registry.go, test/acceptance/features/requirements.txt, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/supportExistingOperatorBackedServices.feature, test/acceptance/resources/apps/sbo-generic-test-app/postgres-ready.sh
Crunchy operator provisions Postgres instances and creates at the same certificates that might be required for some clients.
* added service binding annotation for locating and exposing certificates
* acceptance test updated to assert if postgres connection can be really established
* acceptance test update to assert if the certifactes are projected
* added `provider` binding with value `crunchydata`
* fixed the bug in `test/acceptance/resources/apps/sbo-generic-test-app/postgres-ready.sh` - password can contain special characters and hence needs to be urlencoded before constructing Postgres connection url.
* `polling2` library updated to 0.5.0 so that polling decorator can be used to implement `assert_file_exist` method in `test/acceptance/features/steps/generic_testapp.py`
Related to …
=> Project certificates together with other Crunchy Postgres bindings

samples/apps/spring-petclinic/Dockerfile.app, samples/apps/spring-petclinic/Makefile, samples/apps/spring-petclinic/app-deployment.yaml, samples/apps/spring-petclinic/db-deployment.yaml, samples/apps/spring-petclinic/minikube/deploy-app.sh, samples/apps/spring-petclinic/openshift/deploy-app.sh, samples/apps/spring-petclinic/patch/pom.xml.patch, samples/apps/spring-petclinic/service-binding.yaml
Current quickstart uses only REST API server part of the Spring Petclinic as an application and Crunchy Postgresql Operator backed DB. It has couple of UX issues.
The current application:
* does not have UI so user must use `kubectl port-forward` and `curl` command to send requests to the application's API server and analyze responses for accessing and verifying that the application works as expected
* user has to manually run a script to initialize database with application schema and data (as one of the quickstart's steps)
The current database:
* requires installation of Crunchy Postgresql Operator (via OLM) that wouldn't be possible for user with kubernetes cluster without OLM
* uses an operator that is not available on other then `x86_64` architectures, which excludes all users on …
=> Introduce sample application (spring-petclinic + postgresql) to be used in quickstart

Makefile
We need this to enable local testing on `minikube` clusters; cert-manager's `v1beta1` resources were deprecated.
Updates the `deploy-cert-manager` make rule to use cert-manager v1.6.0.
Deploy a cluster using `make deploy`.
=> Upgrade cert manager from v1.1.0 to v1.6.0

test/acceptance/features/supportExistingOperatorBackedServices.feature
Currently the Cloud Native Postgres operator is not available among certified operators for OpenShift 4.10 (since 4.10 is yet to be released) and so the respective scenario fails for all PRs.
This PR:
* Along with https://github.com/openshift/release/pull/25188 this PR temporarily disables Cloud Native Postgres operator scenario for openshift 4.10
PR checks
=> Temporarily disable Cloud Native Postgres operator scenario for openshift 4.10

hack/prepare-operatorhub-pr.sh
Ref.
https://stackoverflow.com/questions/22697688/how-to-cat-eof-a-file-containing-code
The `stable` text is getting evaluted and producing an error.
=> Avoid expression evaluation in the script

test/acceptance/features/steps/crunchypostgresoperator.py
Currently, the Crunchy Postgres Operator in acceptance tests running on OpenShift uses `community-operators` catalog source to install the operator for testing.
The above operator is currently not available in `community-operators` catalog for not-yet-released OpenShift v4.10 which causes the `4.10-acceptance` to fail constantly.
However, the operator is available in the `certified-operators` catalog for all the tested version of OpenShift.
This PR:
* Changes the catalog source from which the `Crunchy Postgres Operator` is installed for testing with OpenShift to `certified-operators`.
included if any functionality added or changed. For bugfixes please include tests that can …
=> Use certified-operators catalog source for Crunchy Postgres Operator in acceptance tests

Makefile, hack/prepare-operatorhub-pr.sh
Currently, when performing a release to Operatorhub.io a manual step is required to set the bundle channel to `stable` in the `metadata/annotations.yaml` file after `make prepare-operatorhub-pr` is executed (as described in [`docs/community-release.md`](https://github.com/redhat-developer/service-binding-operator/blob/40a4671acbbdcb0c80acc697d8525cfac2f3bfd9/docs/community-release.md#community-release)).
This PR:
* Modifies the `hack/prepare-operatorhub-pr.sh` script to set both the `operators.operatorframework.io.bundle.channel.default.v1` and `operators.operatorframework.io.bundle.channels.v1` to `stable` so that the above mentioned manual step is not required.
included if any …
=> Set channels to 'stable' for Operatorhub.io PR metadata

.github/workflows/merge-to-master.yaml
Currently merge-to-master GH action fails to release the SBO to quay.io because of old version of operator-sdk (pre-#1094) used.
Fixes merge-to-master GH action missed by #1094 
=> Fix operator-sdk version  in merge-to-master GH action

.github/actions/collect-kube-resources/action.yaml
Currently, in GitHub actions for acceptance testing PR checks a set of kube resources is collected and archived for possible debugging or failures analysis. What is missing and can be quite useful are the actual Pod logs.
This PR:
* Modifies the `./.github/actions/collect-kube-resources` GH action to collect and include logs from Pods in operator and test namespaces.
=> Include pod logs while collecting kube resources in GitHub actions

samples/apps/spring-petclinic/mysqlcluster-deployment.yaml, samples/apps/spring-petclinic/petclinic-mysql-deployment.yaml
This PR adds  yaml files to samples/apps/spring-petclinic which are used to create spring petclinic application deployment compatible with mysql and also the custom resource yaml for creating instance of PerconaXtraDB cluster
=> Added Spring Petclinic Application Deployment  yaml compatible with MySQL and custom resource yaml for creating instance of PerconaXtraDB cluster

test/acceptance/features/steps/cloudnativepostgresoperator.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
Currently the Cloud Native Postgres operator is not available among certified operators for OpenShift 4.10 and 4.11 and so the respective scenario fails for all PRs.
This PR:
* Changes the catalog source to install Cloud Native Postgres operator from to [Operatorhub.io](https://operatorhub.io/operator/cloud-native-postgresql)
* Re-enables Cloud Native Postgres operator scenario for OpenShift 4.10
PR checks
=> Re-enable Cloud Native Postgres operator scenario for openshift 4.10 and switch catalog source to Operatorhub.io

.github/pull_request_template.md, test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToProvisionedService.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/discoverBindableResources.feature, test/acceptance/features/gettingStartedGuide.feature, test/acceptance/features/immutableBindings.feature, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/supportExistingOperatorBackedServices.feature, test/acceptance/features/unbindAppToService.feature
This PR:
* Adds the `@external-feedback` tag to the acceptance scenarios that has been added as a result of an external feedback such as a bug report (to verify that the bug was fixed) or a feature request (to ensure the feature's behavior is as expected).
* Adds an item to the Submitter Checklist in the PR template to ensure that `All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with "@external-feedback" tag.`
This would allow to measure the amount of QE adoption of the external feedback in terms or (number of scenarios based on external feedback)/(number of all scenarios) and so the quality maturity.
As the author of this PR, please check off the items in …
=> Tag acceptance testing scenarios that are a result of external users' feedback

test/acceptance/features/gettingStartedGuide.feature, test/acceptance/features/supportExistingOperatorBackedServices.feature
Currently, all acceptance tests assume that SBO to be installed in Kubernetes or OpenShift clusters deployed on `amd64` machines.
While SBO itself can run on the alternative architectures, some of the acceptance tests scenarios cannot.
This PR:
* Introduces tags to diable scenarios/feature for various alternative architectures (`@disable.arch.ppc64le`, `@disable.arch.s390x`, `@disable.arch.arm64`)
* Marks scenarios that cannot run on respective architectures with those tags.
To disable those scenarios, append the following into `EXTRA_BEHAVE_ARGS` env variable for that acceptance test run: 
```
EXTRA_BEHAVE_ARGS="... --tags=~@disable.arch.<arch> ..."
```
included if …
=> Disable scenarios for architectures other then amd64

go.mod, pkg/binding/annotationmapper.go, pkg/reconcile/pipeline/builder/pipeline_test.go, vendor/modules.txt
The github.com/pkg/errors package is no more maintaned:
https://github.com/pkg/errors/issues/245
=> Remove the last usage of obsolete package

.github/workflows/pr-checks.yaml
`codecov/codecov-action@v1` has been [deprecated](https://github.com/marketplace/actions/codecov#%EF%B8%8F--deprecration-of-v1), so this PR upgrades the version to the latest version ATM (`v3`)
=> Upgrade codecov-action from deprecated v1 to v3

.github/workflows/merge-to-master.yaml
Followup to #1129 which missed `merge-to-master` workflow. That caused the PR check coverage data and those for `master` used as a base for comparison to differ and as a result always to fail the CodeCov PR check.
This PR:
* upgrades the codecov-action to version `v3` matching the PR checks.
=> Upgrade codecov-action from deprecated v1 to v3 for merge-to-master

test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py
Recently, the Crunchy PostgreSQL Operator has been released to version `5.1.0` in [Operatorhub.io](https://operatorhub.io/operator/postgresql/). That version of the operator has set the minimal version of k8s to `v1.20.0` which is incompatible with our acceptance tests executed with Minikube which is set to k8s `v1.19.2`.
Additionally, the acceptance tests are set to install the latest version of Crunchy PostgreSQL Operator.
That causes the acceptance tests using the Crunchy PostgreSQL Operator to fail because the operator is not being installed properly into the Minikube cluster.
This PR:
* Pins the version of Crunchy PostgreSQL Operator for acceptance tests with Minikube to `v5.0.5` which is still compatible with k8s `v1.19.2`
As the …
=> Pin Crunchy PostgreSQL Operator version to v5.0.5 for acceptance tests with Minikube

test/acceptance/openshift-setup.sh
=> Create non-admin user for acceptance tests for OpenShift only if it does not exist

test/acceptance/features/steps/service_binding.py
One of the `Service Binding is ready` step's assertions is to compare SB `generation` and `observedGeneration`. There is a typo in the both JSON paths, both resulting in Error and returning a `None` value.
This can be spotted in the test std output:
```
,---------,-
| COMMAND : kubectl get servicebindings.servicebinding.io bindapptoprovisionedservice-246-binding -o "jsonpath={.metadata.generation" -n test-ns-d58f
'---------'-
ERROR MESSGE: b'error: error parsing jsonpath {.metadata.generation, unclosed action\n'
ERROR CODE: 1
Error getting value for servicebindings.servicebinding.io/bindapptoprovisionedservice-246-binding in test-ns-d58f path={.metadata.generation: error: error parsing jsonpath {.metadata.generation, unclosed action …
```
=> Fix 'Service Binding is ready' step assertions

samples/apps/spring-petclinic/Makefile, samples/apps/spring-petclinic/petclinic-mysqlcluster-binding.yaml
issue: #1124
Added petclinic-mysqlcluster-binding.yaml containing a manifest for the ServiceBinding.
Added the following  make targets:
- deploy-mysqlcluster: to create the cluster
- deploy-app-mysql: to create the modified Spring-Petclinic Application
- bind-mysqlcluster: to create the ServiceBinding
- unbind-mysqlcluster: to delete the ServiceBinding
=> Add missing manifest and make targets for MySQL Cluster Sample

controllers/common.go, docs/userguide/modules/creating-service-bindings/pages/binding-options.adoc, go.mod, main.go, pkg/reconcile/pipeline/api.go, pkg/reconcile/pipeline/builder/pipeline.go, pkg/reconcile/pipeline/builder/pipeline_integration_test.go, pkg/reconcile/pipeline/builder/pipeline_test.go, pkg/reconcile/pipeline/context/flow_ctrl.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, pkg/reconcile/pipeline/context/spec_binding_impl.go, pkg/reconcile/pipeline/context/spec_binding_impl_test.go, pkg/reconcile/pipeline/handler/project/impl.go, pkg/reconcile/pipeline/handler/project/impl_test.go, pkg/reconcile/pipeline/mapping.go, pkg/reconcile/pipeline/mapping_test.go, pkg/reconcile/pipeline/mocks/mocks_pipeline.go, test/acceptance/features/bindMultipleAppsToSingleService.feature, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/steps.py, vendor/modules.txt
Workloads that we bound with label selectors won't get bound if they
were created after the service binding was first reconciled.  As a
workaround, periodically reconcile service bindings with label selectors
to pick up any new workloads.
This uses an exponential backoff strategy, which is the default for when
a duration before re-reconciling is not specified.  A fixed interval was
considered, but was decided against out of concerns for thundering herd
problems in a cluster.
=> bind labeled workloads created after sb reconcile

charts/service-binding-operator/.helmignore, charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/LICENSE.md, charts/service-binding-operator/README.md, charts/service-binding-operator/crds/bindablekinds.binding.operators.coreos.com.yaml, charts/service-binding-operator/crds/servicebindings.binding.operators.coreos.com.yaml, charts/service-binding-operator/crds/servicebindings.servicebinding.io.yaml, charts/service-binding-operator/templates/_helpers.tpl, charts/service-binding-operator/templates/certificate.yaml, charts/service-binding-operator/templates/clusterrole.yaml, charts/service-binding-operator/templates/clusterrolebinding.yaml, charts/service-binding-operator/templates/configMap.yaml, charts/service-binding-operator/templates/deployment.yaml, charts/service-binding-operator/templates/issuer.yaml, charts/service-binding-operator/templates/role.yaml, charts/service-binding-operator/templates/rolebinding.yaml, charts/service-binding-operator/templates/service-account.yaml, charts/service-binding-operator/templates/service.yaml, charts/service-binding-operator/templates/tests/test-service-binding-operator-connection.yaml, charts/service-binding-operator/templates/webhook.yaml, charts/service-binding-operator/values.schema.json, charts/service-binding-operator/values.yaml, docs/userguide/modules/getting-started/pages/installing-service-binding.adoc, test/charts/service-binding-operator/Dockerfile, test/charts/service-binding-operator/application.yaml, test/charts/service-binding-operator/sbo.yaml, test/charts/service-binding-operator/secret.yaml, test/charts/service-binding-operator/test-entrypoint.sh
This PR defines the Service Binding Operator Helm chart.
=> Service Binding Operator Helm chart

.github/actions/check-skip-acceptance-tests/action.yaml, .github/workflows/pr-checks.yaml
Currently, the acceptance tests are executed for any and each PR - even for those that for example affects only the docs. In such cases there is no need to actually execute the acceptnace tests as the resulting SBO images as well as the testing framework (incl. scenarios) are exactly the same as those already tested and merged in master.
Not running the acceptance tests for PRs that do not inflict any testable changes would save time significantly to merge such PRs as well as saving resources
Ref: https://issues.redhat.com/browse/APPSVC-1116
included if any functionality added or changed. For bugfixes please include tests that …
=> Skip running acceptance tests in GH workflows for PR that does not change SBO nor the testing framework

test/performance/collect-kpi.sh, test/performance/collect-results.sh, test/performance/deploy-sbr.sh, test/performance/kpi.py, test/performance/kpidiff.py, test/performance/run.sh, test/performance/user-workloads/incomplete/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/invalid/sbo-test.sbr.spec.yaml, test/performance/user-workloads/invalid/sbo-test.sbr.yaml, test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml, test/performance/user-workloads/valid/sbo-test.sbr.spec.yaml, test/performance/user-workloads/valid/sbo-test.sbr.yaml, test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
Ref:
* https://issues.redhat.com/browse/APPSVC-1109
* https://issues.redhat.com/browse/APPSVC-1122
This PR:
* Extends performance testing framework to support SPEC API resources
* SPEC API resources are added as user workloads to be used along with CoreOS resources in the performance test
* Adds workload resource mapping for `cronjobs.batch` resources
* Adds `CronJob` as one of the workloads to be bound and a `ServiceBinding` resource to bind it
* Adds service binding with a label selector in the `incomplete` scenario
* The overall number of simulated users is kept
included if any functionality added or changed. For bugfixes …
=> Add support for servicebinding.io API for performance testing

make/build.mk
Currently, the bundle manifests generated by `make bundle` follow a certain naming convention: `service-binding-<name>-<group>_<version>-<kind>.yaml` except for the `clusterrole-service-binding-controller-role.yaml` and `clusterrolebinding-service-binding-controller-rolebinding.yaml` files.
For the RedHat downstream releases, those 2 files need to be manually renamed to follow the above naming convention.
This PR:
* Fixes the generated names of the above 2 files to follow the bundle manifest's file naming convention
=> Fix generated filenames for controller role and rolebinding to follow naming convention in bundle

.github/actions/check-skip-acceptance-tests/action.yaml, .github/workflows/pr-labels.yaml
Follow-up to: https://github.com/redhat-developer/service-binding-operator/pull/1150
This PR:
* Extends the `check-skip-acceptance-tests` GitHub Action to be able to set or unset the specified label on a PR that can skip (or can't skip resp.)
* Adds a `pull_request_target` scoped workflow using that action to set or unset `acceptance-tests-skipped` label
=> Add/Remove acceptance-tests-skipped label for PRs

PROJECT, apis/spec/v1alpha3/clusterworkloadresourcemapping_types.go, apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook.go, apis/spec/v1alpha3/clusterworkloadresourcemapping_webhook_test.go, config/crd/bases/binding.operators.coreos.com_bindablekinds.yaml, config/crd/bases/binding.operators.coreos.com_servicebindings.yaml, config/crd/bases/servicebinding.io_clusterworkloadresourcemappings.yaml, config/crd/bases/servicebinding.io_servicebindings.yaml, config/rbac/role.yaml, config/webhook/manifests.yaml, main.go, test/acceptance/features/steps/steps.py, test/acceptance/features/workloadResourceMapping.feature
Implement validation webhooks for incoming & modified ClusterWorkloadResourceMapping.servicebinding.io resources.  Deletion is left unhandled; it's not clear if we need to implement deletion validation.
=> webhooks: validate workload resource mapping resources

docs/userguide/modules/binding-workloads-using-sbo/pages/creating-service-binding.adoc, docs/userguide/modules/exposing-binding-data/pages/provisioned-service.adoc
The specification hasn't used the noun "application" to refer to workloads for a little while, but our documentation still had a few references to that terminology.  This changes them to use "workload" instead.
/kind docs
=> docs: use workload terminology for spec API

.github/workflows/merge-to-master.yaml, .github/workflows/pr-checks.yaml, make/version.mk
Ref: https://issues.redhat.com/browse/APPSVC-1136
=> Add GH action for security scan.

pkg/reconcile/pipeline/context/impl.go
Related to: #1172 
Currently, if error occurs which is related to getting Subject Access Review for a ClusterWorkloadResourceMapping resources. The error is not shown to explain the reason and only the `false` value is returned.
This PR adds an error log for such events to see the root cause of the error.
=> Print subject access review error to logs.

config/rbac/clusterworkloadresourcemappings_viewer_role.yaml, config/rbac/clusterworkloadresourcemappings_viewer_rolebinding.yaml, config/rbac/kustomization.yaml
There are cluster role and binding missing to read the CWRM resources to any users. This is something that (according to the dev sandbox team) is not part of the dev sandbox configuration, but is supposed to be part of the SBO bundle - similarly as in case of the `BindableKinds` resource.
This PR adds missing `ClusterRole` and `ClusterRoleBinding` for reading (`get`, `list`, `watch`) the `ClusterWorkloadResourceMapping` resources to any authenticated subject (incl. dev sandbox users).
=> Add missing cluster role and binding for reading ClusterWorkloadResourceMapping for any authenticated subject

.github/workflows/merge-to-master.yaml, .github/workflows/pr-checks.yaml
=> Ignore security warnings without known fixes

samples/apps/spring-elasticsearch/Dockerfile.app, samples/apps/spring-petclinic/Dockerfile.app
Updates the sample apps to the latest upstreams.  Please `make push-app-multiarch` in each directory to propogate new builds.
=> Update sample apps

test/acceptance/features/bindAppToProvisionedService.feature
=> Add negative scenario for Provisioned Service referencing non-existing secret

.github/actions/check-skip-acceptance-tests/action.yaml
Currently the skip detector misses the main `Dockerfile` as in case of #1166. This PR:
* Includes the main `Dockerfile`
* Changes the filter to match files exactly (instead of using `.startsWith` method as for directories)
The skipping filter for acceptance tests with OpenShift (CI) is covered by https://github.com/openshift/release/pull/29427
=> Do not skip acceptance tests if the main Dockerfile is changed.

.github/workflows/pr-checks.yaml, hack/collect-kube-resources.sh, test/acceptance/features/workloadResourceMapping.feature
Currently, when acceptance tests fail, the kube resources are not collected and archived by GH actions for debug purposes.
Additionally, one of the acceptance tests started to fail recently in the Kubernetes with OLM job due to too many pods being created in the minikube. That prevented creation of the pods for the test which caused the test to fail.
This PR:
* Enables collecting and archiving kube resources for GH actions for situations when acceptance tests failed.
* Moves Workload Resource Mapping PR Check acceptance tests to the separate job.
included if any functionality added or changed. For bugfixes please include tests …
=> fix(ci): collect kube resources and split acceptance testing jobs

test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/subscription_install_mode.py
Ref: https://issues.redhat.com/browse/APPSVC-1151
This PR:
* Extends the `Operator.install_operator_subscription()` method with additional optional parameter `install_node` (with "Automatic" as the default).
* The method also automatically approves the related InstallPlan if install_mode is "Manual".
=> Extend the acceptance testing framework to support installing operator with both manual and automatic subscriptions

docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
=> Add docs to set permissions due to Kubernetes bug

docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
=> Correct asciidoc syntax for link

go.sum, make/lint.mk, pkg/client/kubernetes/whoami.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/spec_binding_impl.go
This PR:
* Updates golangci-lint to latest version
* Splits execution of individual Go linters
* Fixes new issues found by the newer versions of the linters
=> Tweak golangci-lint to avoid out-of-memory in Github Actions

CONTRIBUTING.md, DCO
=> Update DCO to align with redhat-developer organization guidelines.

test/acceptance/features/steps/cloudnativepostgresoperator.py, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/percona_mysql_operator.py, test/acceptance/features/steps/perconamongodboperator.py, test/acceptance/features/steps/rabbitmq_operator.py, test/acceptance/features/steps/redisoperator.py, test/acceptance/features/steps/serverless_operator.py
Currently, the `Operator` class uses class attributes such as `Openshift.operators_namespace` and `Openshift.olm_namespace` to define what namespace to install the operator in and the namespace for catalog source.
That information is supposed to be local to the operator class but the `Operator` class uses the 
`Openshift` class attributes (which is shared between all instances of that class) for setting those namespaces for the instances of the operator. That is fine when the namespaces are the default ones (`operators` or `openshift-operators` and `olm` or `openshift-marketplace` respectively).
In order to change the namespace for the operator or the catalog source the operator currently changes the `Openshift.operators_namespace` or the …
=> Fix hidden dependency between scenarios in acceptance tests

make/deploy.mk
Bumps the auto-deployed version of cert-manager to v1.9.1, the latest release.
=> Upgrade cert-manager release to v1.9.1

docs/userguide/modules/getting-started/partials/creating-db-pgcluster.adoc, samples/apps/spring-petclinic/pgcluster-deployment.yaml, test/acceptance/features/steps/command.py, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/steps/getting_started.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
=> Update Crunchy postgres operator version to v5.1.2

docs/userguide/modules/projecting-binding-data/pages/projecting-binding-data.adoc
=> Document rebind behavior

test/acceptance/features/steps/openshift.py
We don't need the resiliancy of 3 replicas for generic-test-app deployments during acceptance tests.  Explicitly set `replicas: 1` in our deployments to reduce pod utilization.
/kind bug
=> Use fewer pod replicas in testing deployments

pkg/reconcile/pipeline/api.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, pkg/reconcile/pipeline/context/spec_binding_impl_test.go, pkg/reconcile/pipeline/handler/project/impl.go, pkg/reconcile/pipeline/handler/project/impl_test.go, pkg/reconcile/pipeline/mocks/mocks_pipeline.go, test/acceptance/features/bindAppToServiceAnnotations.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature
This exposes the relevant binding secret without requiring a workload to be present.
=> Expose binding secret without requiring a workload

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
In preparation for release of SB 1.2.0
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
=> Bump Version 1.2.0

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
=> Update operator manifests with spec v1beta1 resources

docs/userguide/modules/binding-workloads-using-sbo/nav.adoc, docs/userguide/modules/binding-workloads-using-sbo/pages/api-differences.adoc
Explicitly documents the difference between the two APIs we support.
=> docs: difference between coreos & spec API

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/README.md, charts/service-binding-operator/crds/clusterworkloadresourcemappings.servicebinding.io.yaml, charts/service-binding-operator/crds/servicebindings.servicebinding.io.yaml, charts/service-binding-operator/templates/clusterrole.yaml, charts/service-binding-operator/templates/deployment.yaml, charts/service-binding-operator/templates/tests/test-service-binding-operator-connection.yaml, charts/service-binding-operator/values.schema.json, charts/service-binding-operator/values.yaml
This PR updates the  chart  directory with service binding operator 1.2.0 source chart.
=> Update chart directory  with service binding operator 1.2.0

test/performance/collect-results.sh
=> Fix result collecting script in performance test

controllers/crd/crd_controller.go
This might help with the errors we were seeing in OCP 4.11 logs.
/kind bug
=> Ignore non-served crds in the crd controller

controllers/crd/crd_controller.go
This might help with the errors we were seeing in OCP 4.11 logs.
/kind bug
=> cherry-pick(release-v1.2.x): crds: Ignore non-served versions in crd controller

test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature
Tags the acceptance testing scenarios that use OLM descriptors by the `@olm-descriptors` tag.
=> Tag OLM Descriptor related tests by @olm-descriptor tag

test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature
Tags the acceptance testing scenarios that use OLM descriptors by the `@olm-descriptors` tag.
=> cherry-pick(release-v1.2.x): Tag OLM Descriptor related tests by @olm-descriptor tag

test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
=> cherry-pick(release-v1.3.x): Ensure the desired install plan is approved in acceptance tests

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
=> Bump version to v1.3.0

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
This PR updates the charts directory with service binding operator 1.3.0 chart.
=> update chart with  service binding operator 1.3.0

.github/workflows/pr-checks.yaml, samples/apps/spring-petclinic/pgcluster-deployment.yaml, test/acceptance/features/gettingStartedGuide.feature, test/acceptance/features/steps/cloudnativepostgresoperator.py, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
Currently:
* Latest Crunchy Postgres Operator (v5.2.0) is not compatible with OCP 4.12 due to https://github.com/CrunchyData/postgres-operator-examples/issues/151
* Latest Percona Mysql Operator fails to install on OCP 4.12 
=> cherry-pick(release-v1.3.x): Fix or temporarily disable tests for supported operators that does not currently work with OCP 4.12

.github/workflows/pr-checks.yaml, samples/apps/spring-petclinic/pgcluster-deployment.yaml, test/acceptance/features/gettingStartedGuide.feature, test/acceptance/features/steps/cloudnativepostgresoperator.py, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
Currently:
* Latest Crunchy Postgres Operator (v5.2.0) is not compatible with OCP 4.12 due to https://github.com/CrunchyData/postgres-operator-examples/issues/151
* Latest Percona Mysql Operator fails to install on OCP 4.12 
=> cherry-pick(release-v1.2.x): Fix or temporarily disable tests for supported operators that does not currently work with OCP 4.12

.github/workflows/pr-cherry-pick-clean.yaml, .github/workflows/pr-cherry-picks.yaml
This PR adds GH workflows to automate release-branch cherry-picking process. It goes as follows - as soon as the release-labeled PR to master is merged:
* A cherry-pick PR branch is created based on the release branch label of the original PR
* Original PR commit from master is cherry-picked and added on top of the cherry-pick PR branch
* A cherry-pick PR is sent from the cherry-pick PR branch to the release branch
* Normal PR checking flow is excercised including all the CI and approval
* Once the cherry-pick PR is merged the cherry-pick PR branch is deleted
=> Add GH workflows for cherry-picking PRs to release branches

make/common.mk, make/performance.mk
This PR:
* Introduces `test-performance-thresholds` Makefile targed that compares various vaules from `kpi.yaml` generated by `make test-performance-collect-kpi` to the threshold values defined in environment variables `TEST_PERFORMANCE_AVG_MEMORY`, `TEST_PERFORMANCE_MAX_MEMORY`, `TEST_PERFORMANCE_AVG_CPU`, `TEST_PERFORMANCE_MAX_CPU`. If any of the threshold is crossed it fails.
* The `test-performance-thresholds` is to be executed as part of `performance*` OpenShift CI jobs (https://github.com/openshift/release/pull/33192) (after the `test-performance-collect-kpi` step) and fails the job if any of the thresholds is crossed. …
=> Compare various KPIs to the threshold values and fail if any is crossed

.github/actions/check-skip-acceptance-tests/action.yaml, .github/workflows/merge-to-master.yaml, .github/workflows/merge-to-release-branch.yaml, .github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks-clean-images.yaml, .github/workflows/pr-checks-push-images.yaml, .github/workflows/pr-checks.yaml, .github/workflows/pr-cherry-picks.yaml, .github/workflows/pr-labels.yaml
Github Actions give the following warning about deprecating node12 based actions:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: ...
```
and the following warning about deprecating use of `set-output` command:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
This PR:
* Updates version of actions that use `node12` to versions that use `node16`.
* Replaces …
=> Stop using deprecated features in GH actions

CONTRIBUTING.md, make/acceptance.mk, make/build.mk, make/common.mk, make/deploy.mk
If required tool version is found on the host, then it will be linked into the ./bin folder. Otherwise, it will be downloaded.
Signed-off-by: Francesco Ilario <filario@redhat.com>
Added `install-tools` and `local-env` rules to makefiles.
Leveraging on these rules, it is now possible to easily install the needed version of each dependency.
=> Add install-tools and local-env rules to Makefiles

README.md, pkg/binding/registry/registry.go, test/acceptance/features/supportExistingOperatorBackedServices.feature
=> Fix Percona MongoDB operator support

make/deploy.mk
Fix an error in the deploy/uninstall rule.
The kubectl dependency was added to .PHONY instead of to the uninstall rule's dependencies.
/kind bug
=> Fix deploy/uninstall rule

config/samples/kustomization.yaml, config/samples/operators_v1alpha1_bindablekinds.yaml, config/samples/spec_v1alpha3_clusterworkloadresourcemapping.yaml, config/samples/spec_v1alpha3_servicebinding.yaml, config/samples/spec_v1beta1_servicebinding.yaml
=> Fix resource samples in CSV

apis/common.go, apis/spec/v1beta1/clusterworkloadresourcemapping_webhook.go, apis/spec/v1beta1/clusterworkloadresourcemapping_webhook_test.go, apis/webhooks/suite_test.go, apis/webhooks/validator.go, apis/webhooks/validator_test.go, controllers/common.go, main.go, pkg/reconcile/pipeline/api.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/context/impl_test.go, pkg/reconcile/pipeline/context/spec_binding_impl.go, pkg/reconcile/pipeline/context/spec_binding_impl_test.go, pkg/reconcile/pipeline/handler/mapping/impl.go, pkg/reconcile/pipeline/handler/project/impl.go, pkg/reconcile/pipeline/handler/project/impl_test.go, pkg/reconcile/pipeline/mocks/mocks_pipeline.go, test/acceptance/features/steps/app.py, test/acceptance/features/workloadResourceMapping.feature
This works in three stages:
1. During workload mapping's validation webhook, we serialize the old mapping into the `servicebinding.io/mapping` annotation on all relevant service bindings.
2. We run our reconcile pipeline once, to unbind the workload using the serialized mapping.  Once completed, we delete the mapping and immediate trigger reprocessing of the service binding.
3. We re-run our reconcile pipeline as normal using the new mapping to project data as expected.
=> Rebind workloads when their mappings change

.github/workflows/merge-to-master.yaml, .github/workflows/merge-to-release-branch.yaml, .github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks.yaml, Dockerfile, go.mod, go.sum, test/_projects/api-client/go.mod, test/_projects/api-controller/go.mod
Red Hat UBI8 based image for Go 1.18 is available: `registry.redhat.io/rhel8/go-toolset:1.18` so we can bump go version to 1.18. (Go 1.17 is out-of-life already)
=> Bump version of Go to v1.18

pkg/reconcile/pipeline/context/service/crd_test.go, pkg/reconcile/pipeline/context/service/service.go, test/acceptance/resources/backend_crd.yaml
=> Detect bindable resource based on status attribute

test/acceptance/features/steps/perconamongodboperator.py
Currently, Percona MongoDB operator is not available in `community-operators` catalog for OpenShift 4.12 which causes the acceptance testing PR checks for OpenShift 4.12 to fail.
This PR:
* Changes the catalog for Percona MongoDB operator on OpenShift in tests from the `community-operators` to Operatorhub.io.
=> Use community version of Percona MongoDB Operator in acceptance tests on OpenShift

test/acceptance/features/steps/perconamongodboperator.py
Currently, Percona MongoDB operator is not available in `community-operators` catalog for OpenShift 4.12 which causes the acceptance testing PR checks for OpenShift 4.12 to fail.
This PR:
* Changes the catalog for Percona MongoDB operator on OpenShift in tests from the `community-operators` to Operatorhub.io.
=> cherry-pick(release-v1.3.x): Use community version of Percona MongoDB Operator in acceptance tests

test/acceptance/features/steps/servicebindingoperator.py
The acceptance testing framework is not working properly with `oc` `v4.9` - it assumes parameters of `oc` (the `--for=jsonpath=...` option for `oc wait` subcommand) that are available in later versions (`v4.10+`) but not yet available in `v4.9`.
Dependency for https://github.com/openshift/release/pull/34341
This PR:
* Fix the framework for OCP 4.9 by replacing the `oc wait --for=jsonpath='...'` command with polling the command `oc get ...` for expected response (with use of `polling2` Python library)
* Depends on: https://github.com/redhat-developer/service-binding-operator/pull/1311
included if any functionality added or …
=> Fix SBO checks for OpenShift 4.9

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
Bumps the version in our help chart manifest to v1.3.2.
=> bump version to v1.3.2 for helm chart

.github/workflows/pr-checks.yaml, samples/apps/spring-petclinic/pgcluster-deployment.yaml, test/acceptance/features/steps/crunchypostgresoperator.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
=> Update Crunchy Postgres Operator to v5.3.0 in acceptance tests

hack/check-python/prepare-env.sh, test/performance/kpidiff.py
=> Include test/performance in Python linter

controllers/spec/servicebinding_controller.go, main.go
=> Remove reconciler for spec v1alpha3 version

make/performance.mk, test/performance/requirements.txt, test/performance/upload_data.py
Adding support for uploading performance kpi metrics to the opensearch instance as part of the story: https://issues.redhat.com/browse/APPSVC-1261
=> Adding support to upload performance kpi data to opensearch

make/build.mk
Use `-ldflags="-s -w"` and `-trimpath` in `go build` to strip debug tables and system paths from final binary.
From [https://pkg.go.dev/cmd/link](https://pkg.go.dev/cmd/link):
- `-s`: Omit the symbol table and debug information
- `-w`: Omit the DWARF symbol table.
From [https://pkg.go.dev/cmd/go](https://pkg.go.dev/cmd/go):
- `trimpath`: remove all file system paths from the resulting executable. Instead of absolute file system paths, the recorded file names will begin either a module path@version (when using modules), or a plain import path (when using the standard library, or GOPATH).
included if any functionality added or changed. For bugfixes please include …
=> Remove debug info from final binary

make/performance.mk
Signed-off-by: Sushanta Das <sushanta.das.ju@gmail.com>
This PR will fix the environment issue observed while uploading performance kpi data during periodic CI job here https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/34971/rehearse-34971-periodic-ci-redhat-developer-service-binding-operator-master-4.11-performance-latest-openshift/1606303067391660032
Since the upload_data.py script is running in virtual environment, the env variables from the make file needs to be passed explicitly.
=> Fixed the environment issue in CI

.github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks.yaml, .gitignore, hack/upgrade-sbo-env.sh, make/acceptance.mk, make/build.mk, make/version.mk, test/acceptance/features/environment.py, test/acceptance/features/steps/environment.py, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/servicebindingoperator.py, test/acceptance/features/steps/steps.py, test/acceptance/features/steps/util.py, test/acceptance/features/upgradeSBOwithOLM.feature
This PR:
* Updates the PR index image to have 2 bundles, the "latest master" from the `quay.io/redhat-developer/servicebinding-operator:index` image and the PR bundle image itself set to replace the "latest master" version.
* Includes a PR commit ID in the PR bundle version
* Depends on https://github.com/openshift/release/pull/33433
=> cherry-pick(release-v1.3.x): Test upgrade SBO with OLM

test/performance/collect-kpi.sh, test/performance/upload_data.py
Addressed review comments on https://issues.redhat.com/browse/APPSVC-1261 with this PR
=> Added metadata with performance kpi data upload

test/performance/upload_data.py
Changed the type of execution_timestamp parameter to string while sending the data to opensearch. So that it is consistent with upload_time parameter.
=> Fixed the type of execution_timestamp

make/version.mk
Bumps operator version to v1.3.4
=> bump to version v1.3.4

OWNERS
=> remove @pmacik as owner

.github/dependabot.yml
Daily updates for dependabot is a bit much with our current resources, so let's back off to weekly for now.
=> dependabot: adjust update policy to weekly

test/acceptance/features/steps/app.py
Make tests more robust adding a polling on `App.get_generation`
=> Add polling to App.get_generation in tests

.github/workflows/merge-to-master.yaml, .github/workflows/pr-checks.yaml
This was causing some small issues in linting; might as well bump it to latest available.
/kind test
=> ci: bump python version to 3.11

test/acceptance/features/steps/openshift.py
The `--docker-image` flag has been deprecated, so we should move away from using it.
/kind bug
=> test: change oc's --docker-image flag to --image

test/acceptance/features/bindAppToProvisionedService.feature
OpenShift 4.14+ deprecates support for deploymentconfig resources, so we shouldn't run tests that depend on them in those environments.
/kind bug
=> test: disable deployment configs in openshift 4.14

make/version.mk
=> bump version to v1.4.0

.github/workflows/periodic-security-check.yaml
Recently in PRs, we've been getting warnings that our SAST tools don't have a known configuration for some branches.  To fix this warning, we need to add push hooks for `master` and the release branches to run security checks.
/kind bug
=> ci: run security checks on push to branch

.github/workflows/merge-to-master.yaml, .github/workflows/merge-to-release-branch.yaml, .github/workflows/periodic-security-check.yaml
This contains two improvements:
- I misconfigured our periodic security checks back in 39908ed30, and it wasn't caught in review. Turns out it was rather unnecessary with the checks we have in merge-to-master and merge-to-release-branch.  The neutral checks we're seeing are caused by something else; I'll need to investigate to figure out what's going on.
- Rather than waiting within the job itself, we can have the jobs for security checks get triggered when the push to quay is done in both the merge-to-master and merge-to-release-branch is done.  It should save a few seconds during checks, and it means we won't have a runner waiting doing nothing.
/kind bug
included if any …
=> ci: cleanup security checks

test/_projects/api-client/go.mod, test/_projects/api-controller/go.mod
These dependencies had become out-of-sync from each other, and were causing test failures.  Bring them back into alignment.
/kind bug
=> bump k8s.io/api* and friends in test/
