Makefile
The flag has been already set by SDK
=> Remove duplicate `-mod vendor` flag

Makefile
Use `-mod vendor` flag to run test
=> Set GOCACHE & GO111MODULE environment variables

openshift-ci/Dockerfile.registry.build
- Do not copy CRDs
- Remove package.yaml (no more required)
=> Change logic to replace image

Makefile, openshift-ci/Dockerfile.tools
This PR is about creating virtual env for running yamllint than running yamllint directly on system env.
=> Create virtual env for yamllint

README.md
At some point we may want to expand this further into a formal operator user guide document. As a first step, we should describe the goals of the operator and how it works for prospective users.
=> First draft at expanded README file - to describe goals and usage of operator

manifests/service-binding-operator.v0.0.10.clusterserviceversion.yaml
=> The display name was "Operator Service Binding Operator" 

pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/mocks/mocks.go
Fixes https://jira.coreos.com/browse/ODC-1243
=> Support dotted notation in attribute path

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go, pkg/controller/servicebindingrequest/planner.go, test/mocks/mocks.go
=> Use ResourceKind instead of ResourceName

README.md
Understandably, the readme could improve and make it easier. Currently, it is focussed on demonstrating the golden path and I'm trying to ensure that it always works as per the readme. :)
=> Fix up the YAMLs in the readme

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
API required for https://jira.coreos.com/browse/ODC-1425
and
https://github.com/redhat-developer/service-binding-operator/pull/83#pullrequestreview-265506936
=> Add prefixes for mount path and environment vars

deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/retriever.go, test/mocks/mocks.go
Based on x-descriptor value in the CSV file, the secret values will be mounted as files inside the container.
Ref: https://jira.coreos.com/browse/ODC-1324
=> Bind secret values as files into the container

README.md
=> correct README typo

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
If the prefix is not given, there won't be any prefix.
Refer: #92
=> Make envVarPrefix optional

pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go, test/e2e/servicebindingrequest_test.go
Fixes: https://jira.coreos.com/browse/ODC-1425
If prefix is not given, there won't be any prefix.
=> Add environment variable prefix

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/status.go
Partially solves: https://jira.coreos.com/browse/ODC-1327
This PR exposes the binding status - `success`, `failure`, `inProgress`
To Do:
Note:
This PR exposes only one status field `BindingStatus` . There will be follow up PR for exposing other fields.
=> Exposes service binding request status

README.md
Adds status information in README.
=> Adds status information in README

README.md, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/status.go
Partially solves: https://jira.coreos.com/browse/ODC-1327
This PR exposes the secret name in service binding status.
ToDo:
=> Adds secret name in service binding status

pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go, pkg/controller/servicebindingrequest/status.go
This status field has all the objects that were found for that label.
Partially fixes ODC-1327.
Note:
Changes in README will be in a followup PR.
=> Adds ApplicationObjects in status

pkg/controller/servicebindingrequest/controller.go
Our controller doesn't create any pods so this shouldn't be there.
=> Remove sdk generated code for pod creation

pkg/controller/servicebindingrequest/reconciler.go
Add application object name only if it is not already present.
=> Check if application object name is already present

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, manifests/service-binding-operator.servicebindingrequests.crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
This PR:
* Updates the CRD manifest for the release v0.0.17
=> Update CRD manifest for release v0.0.17

pkg/controller/servicebindingrequest/reconciler.go, pkg/controller/servicebindingrequest/reconciler_test.go
Convert texts like `inProgress` to `InProgress`
=> Fix PascalCase in constant values stored in ServiceBindRequest's Status field

contributors.txt
Please review for spelling and completeness! We have to add the external contributors too. Thx!
=> Added file to list names of project contributors

README.md
This PR adds the `test` target in README. It is an important target and should have a place in README.
=> Update README to add test target

CONTRIBUTING.md
File created per Shoubhik's suggestion in: https://github.com/redhat-developer/service-binding-operator/pull/181
=> Adding file to explain contribution process to community members.

Dockerfile.rhel
Adds a Dockerfile that does nothing beyond generating a binary, using RHEL images.
=> Build using RHEL-based image

Makefile
Refer: https://github.com/golangci/golangci-lint/issues/658
=> update GolangCI Lint version

.codecov.yaml
CI has been failing due linting issues, this PR is addressing them.
Fixing- empty value in block mapping.
=> fixes yaml lint

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml, manifests/service-binding-operator.servicebindingrequests.crd.yaml, pkg/controller/servicebindingrequest/binder.go
=> Removes matchLabels and resourceRef from required

deploy/crds/apps_v1alpha1_servicebindingrequest_crd.yaml
Make `customEnvVar` and `detectBindingResource` not required fields
=> Make attributes not required

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go
=> Select target object field by metadata.name

README.md, docs/OperatorBestPractices.md, examples/java_postgresql_customvar/README.md, examples/nodejs_postgresql/README.md
This doc is WIP until doc review/feedback and dependent stories are completed:
* https://jira.coreos.com/browse/APPSVC-157
=> Initial draft of operators' best practices guide

README.md
The updated implementation is smart enough to handle any object type with a valid podSpec.
=> docs: Update to include standard podSpec

pkg/controller/servicebindingrequest/sbrcontroller.go
=> Intermediate secret && configMap update 

manifests/4.3.0/service-binding-operator.v4.3.0.clusterserviceversion.yaml, manifests/4.3.0/servicebindingrequests.apps.openshift.io.crd.yaml
Copied over everything from 
https://github.com/operator-framework/community-operators/tree/master/community-operators/service-binding-operator/0.0.23 to the 4.3 release dir
=> Update 4.3 CRD

test/e2e/servicebindingrequest_test.go
This PR:
* Adds the 4 remaining permutations of the E2E test scenario for Service Binding
* Resolves the [APPSVC-126](https://jira.coreos.com/browse/APPSVC-126)
=> Add remaining permutations to the SBR e2e test.

manifests-upstream/0.0.20/service-binding-operator.v0.0.20.clusterserviceversion.yaml, manifests/4.3/service-binding-operator.v4.3.0.clusterserviceversion.yaml
Updates description field in CSV.
As done in:
https://github.com/operator-framework/community-operators/pull/886
=> Update description field in CSV

build/README.md
=> Add a readme to the dir build/

.travis.yml, Makefile
=> fixes automated travis releases

test/mocks/mocks.go
Have a consistent SBR mock structure.
=> Have a consistent SBR mock

pkg/controller/servicebindingrequest/reconciler.go
Rename gr to gvr since we are fetching resources depending upon group,version, resource
=> Rename gr to gvr

deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
Updates deploy CR
Updates deploy CR to include `resourceRef`
=> Updates deploy cr

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/apis/apps/v1alpha1/zz_generated.openapi.go
resourceref should be optional
=> make resourceref of applicationSelector as optional

Makefile
This PR is to test the periodic job in the openshift ci repo. This target will be triggered every 5 minutes for now to test the functionality of periodics.
The changes in the dev-release target would be further modified according to the WIP PR-  #311
=> testing dev release

Makefile
Adding sleep to exec in the pod and watch for the desired result
=> Add 10 mins sleep to dev-release target

Makefile, test/operator-hub/catalog_source.yaml, test/operator-hub/operator_source.yaml, test/operator-hub/subscription.yaml
Refers - https://issues.redhat.com/browse/APPSVC-392
[WIP]
Pending
=> validation of olm bundles part1

Makefile, hack/dev-release.sh
Here steps have been added for Bundle Validation- 
- Installing operator through operator-source.yaml
- Subscribing to the operator through subscription.yaml
- Checking whether marketplace pod is running
- Checking whether SBR CRDs are present
- Checking the BUNDLE_VERSION and the Version in the installed CSV
- Validating the CSV alm-example by applying it
- Checking whether install-plan pod is up and running
=> OLM Bundle validation part2

hack/dev-release.sh
=> fix if case

Makefile
This reverts commit 0b806da4d16feb1f6b74af6e7f3e88d8c4b835be.
The change was causing issues in other parts.
revert the commit
=> Revert "Export all env variables (#326)"

Makefile, hack/dev-release.sh
Explicitly export all required variables.
=> Export all used environment variables

hack/check-crds.sh, hack/check-csvs.sh, hack/dev-release.sh
=> Check for CSV existence

hack/check-csvs.sh
CSV creation is taking more time
Increase time interval
=> Increase sleep interval for CSV check

Dockerfile.rhel
Manifests is generated on-demand
Remove manifests copying from Dockerfile
=> Remove manifests from Dockerfile

docs/OperatorBestPractices.md
.. for operators with no metadata
=> Remove "Coming Soon"

hack/check-csvs.sh
CSV is namespace scoped.
Use namespace based check
=> Check CSV in default namespace

pkg/controller/servicebindingrequest/retriever.go, pkg/controller/servicebindingrequest/retriever_test.go
Remove unused code
- remove retriever.Retrieve()
- remove associated tests.
Doesn't impact any flow.
=> remove unused funtion Retrieve()

Makefile
Preparations for 0.1.0 release
=> set version to 0.1.0

README.md
Was added in https://github.com/redhat-developer/service-binding-operator/pull/357
=> Update readme to include IBM Cloud operator example

Makefile, hack/validate-release.sh, test/operator-hub/subscription2.yaml
Ref. https://issues.redhat.com/browse/APPSVC-470
After making SBO release through operatorhub.io, validate these releases.
=> Validate SBO releases

Makefile
Include OS and ARCH env vars  and removing hard coding
=> fix issue #377

.travis.yml
Make was running in the wrong directory.
Change to correct directory.
=> Change directory before running make

pkg/controller/servicebindingrequest/custom_env_parser.go, pkg/controller/servicebindingrequest/custom_env_parser_test.go
Sometimes we need a json format custom env var
Add a function json into custom_env_parser to do the json marshal.
=> Introduce "json" function in templating to generate inline "json" as custom env var

README.md, examples/nodejs_postgresql/README.md, examples/nodejs_postgresql_namespaces/README.md, examples/nodejs_postgresql_namespaces/service-binding-request.yaml
Adding an example for binding of an app and db in different namespaces
=> Add example of binding in different namespaces

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml, examples/java_postgresql_customvar/README.md, examples/knative_postgresql_customvar/README.md, examples/nodejs_postgresql/README.md, pkg/apis/apps/v1alpha1/servicebindingrequest_types.go, pkg/controller/servicebindingrequest/binding.go, pkg/controller/servicebindingrequest/reconciler_test.go, test/e2e/servicebindingrequest_test.go
Removes status.bindingStatus in favour of status.Conditions.
Jira story: https://issues.redhat.com/browse/APPSVC-494
=> Remove binding status

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go
For some specific cases, binding to applications need extra fields to be modified other than env/volumes in container spec. For example we need to update revision name in knative service template if it is not empty. Detailed discussion please refer to https://github.com/redhat-developer/service-binding-operator/issues/418
Add  `ExtraFieldsModifier` interface to binder and init it based on the GVR of ApplicationSelector.
If `ExtraFieldsModifier` is not nil and object is modified in `binder.update()`, the func `ModifyExtraFields` of interface`ExtraFieldsModifier`  is called.
Unit test cases are added.
=> add extraFieldsModifier to binder

examples/route_k8s_resource/README.md
Add examples doc for PR https://github.com/redhat-developer/service-binding-operator/pull/367
=> Add example for any resource as a backing service

.travis.yml, Dockerfile.rhel, go.mod, openshift-ci/Dockerfile.tools
=> update go version

README.md
https://issues.redhat.com/browse/APPSVC-627
[1] Adds details about service binding community meeting in README
=> Update README with Service Binding community meeting and mailing list details

README.md
Added a missing link in README.md
=> added link to Binding an Imported App to a Route/Ingress

docs/ci.md
Adding some notes would be helpful for developers.
new docs in markdown format.
NA
=> Add notes to debug e2e tests

examples/route_k8s_resource/README.md
Readme gives malformed json payload and incorrect applicationSelector
Fixed SBR request in route_k8s_resource example, by setting group of applicationSelector and fixing whitespaces for easier copy/pasting.
<< How to test those changes, reference implementation of unit/e2e tests. >>
=> Fixed SBR request in route_k8s_resource example, by setting group of applicationSelector and fixing whitespaces for easier copy/pasting. #526

test/e2e/servicebindingrequest_test.go
Making logs more articulate.
`make test-e2e`
=> Make logs more articulate.

deploy/role.yaml
Update deploy/role.yaml for CRDs and routes.
=> Add roles for crds and routes

deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
Run operator-sdk generate crds on master, resulted in alphabetically arranged endpoints.
=> Ran operator-sdk generate crds on master

pkg/controller/servicebindingrequest/reconciler.go
Fix issue #542 
dependent on #523 , #498 
Please follow steps https://github.com/redhat-developer/service-binding-operator/issues/542#issue-652029225 manually
need to add an e2e test case since garbage collection is involved here. e2e can be taken up after the acceptance tests are in place. 
=> Delete sbr if it's ownerRef resource is deleted

examples/java_postgresql_customvar/README.md, examples/java_postgresql_customvar/service-binding-request.yaml, examples/knative_postgresql_customvar/README.md, examples/knative_postgresql_customvar/service-binding-request.yaml
Fixes https://github.com/redhat-developer/service-binding-operator/issues/575 .
The PR updates the customEnvVar example doc.
=> Update examples for customEnvVar

examples/java_postgresql_customvar/README.md, examples/java_postgresql_customvar/service-binding-request.yaml, examples/knative_postgresql_customvar/README.md, examples/knative_postgresql_customvar/service-binding-request.yaml
Some issues were reported by Shobith while building an acceptance test for KNative and service. Updating docs with a working customEnvVar Scenario for the same
=> Update docs for customEnvVar

test/acceptance/features/bindToService.feature, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py
Acceptance test to verify binding two backing service to a single application.
https://issues.redhat.com/projects/APPSVC/issues/APPSVC-640
To run acceptance test make sure you're using `OC version >=4.5`
=> Add acceptance test scenario: Bind 2 backing services to a single application.

examples/nodejs_etcd_operator/README.md
Update etcd-nodejs example readme with correct steps to follow
Tested on OpenShift 4.x clusters.
=> Fix etcd-nodejs example readme

README.md
fixes for typos and readability
=> fixes to Readme

test/acceptance/features/bindKnativeService.feature, test/acceptance/features/steps/command.py, test/acceptance/features/steps/knative_serving.py, test/acceptance/features/steps/namespace.py, test/acceptance/features/steps/nodejs_application.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/postgres_db.py, test/acceptance/features/steps/quarkus_application.py, test/acceptance/features/steps/quarkus_s2i_builder_image.py, test/acceptance/features/steps/serverless_operator.py, test/acceptance/features/steps/service_binding_request.py, test/acceptance/features/steps/steps.py
https://issues.redhat.com/browse/APPSVC-560
quarkus_postgres scenario implemented as knative service:
> Scenario: Bind an imported quarkus app which is deployed as knative service to PostgreSQL database
>         Given Openshift Serverless Operator is running
>         * Quarkus s2i builder image is present
>         * Knative serving is running
>         * DB "db-demo-knative" is running
=> Acceptance tests-quarkus_posgresql_as_knative_service

pkg/controller/servicebindingrequest/binder.go, pkg/controller/servicebindingrequest/binder_test.go
=> fix issue #648 , service-binding-operator panics if there is a configMapRef in envFrom

OWNERS
This will help with GitHub's PR review auto-assignment.
Update OWNERS file
N/A
=> Remove non-active committer

docs/binding-path.md
Fixes #641
This is an advanced feature which required documentation.
Add a new document file.
Follow the instruction in the docs and make sure it works on a cluster.
=> Document containersPath and secretPath behavior

CONTRIBUTING.md, docs/proposals/README.md, docs/proposals/guidelines/proposal-template.md
Enable us to have a community-driven process to add new features/enhancements.
A new enhancement proposal template inspired from OKD, Kubernetes and https://github.com/redhat-developer/build/tree/master/docs/proposals
N/A
=> docs: Enhancement proposal process

test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/steps.py
Fixes https://issues.redhat.com/browse/APPSVC-680
and https://issues.redhat.com/browse/APPSVC-679
Added test assertions
=> Test secret & configmap  values

Makefile, deploy/olm-catalog/service-binding-operator/service-binding-operator.package.yaml, docs/community-release.md, test/operator-hub/subscription2.yaml
Since 0.2.0 is going to be in another channel. It requires some script changes.
Update validation scripts and document release process.
Need manual verification of each step.
Fixes #652
=> Prepare for 0.2.0 release

test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/bindKnativeService.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature, test/acceptance/features/steps/steps.py
Verifying the intermediate secret is getting populated with the bindable information present in backend service csv.
Ticket: https://issues.redhat.com/browse/APPSVC-645
=> Acceptance test for validating binding using OLM descriptors

test/acceptance/features/bindAppToMultipleServices.feature, test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/etcdcluster.py, test/acceptance/features/steps/etcdoperator.py, test/acceptance/features/steps/nodejs_application.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/quarkus_application.py, test/acceptance/features/steps/steps.py
https://issues.redhat.com/browse/APPSVC-644
bind etcd cluster instance
- Given Etcd operator running
-  Given Etcd cluster "etcd-cluster-example" is created
-  Given Imported Nodejs application "nodejs-todo-etcd" is running
=> [acceptance-tests] Add scenario to validate etcd binding and use of detectBindingResources

test/acceptance/features/bindAppToService.feature
Fixes https://issues.redhat.com/browse/APPSVC-681
Add test case
```
TEST_ACCEPTANCE_TAGS=@wip make test-acceptance VERBOSE=3
```
=> Add test to cover binding using annotations on CRD

test/acceptance/features/customEnvVar.feature, test/acceptance/features/steps/app.py, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py, test/acceptance/resources/apps/sbo-generic-test-app/Dockerfile, test/acceptance/resources/apps/sbo-generic-test-app/conf/lighthttpd.conf, test/acceptance/resources/apps/sbo-generic-test-app/env.sh, test/acceptance/resources/apps/sbo-generic-test-app/start_http
Add acceptance test for Service Binding Request with Custom Environment Variables
To run the test - `make test-acceptance`
=> Add acceptance test for Service Binding Request with Custom Environment Variables

test/acceptance/features/bindAppToMultipleServices.feature
https://issues.redhat.com/browse/APPSVC-660
`make test-acceptance VERBOSE=3`
=> [acceptance-test] Bind two backend services by creating 1 SBR to a single application

README.md
* Add a list of key features and a sample CR.
* The list would help a reader understand what this projects aims to support in master.
* Given that our PR checks validated against OKD 4.4, I've added a dependency on kubernetes v1.17+
=> Feature list & Sample CR

deploy/crds/operators.coreos.com_servicebindings_crd.yaml, pkg/apis/operators/v1alpha1/servicebinding_types.go, pkg/apis/operators/v1alpha1/zz_generated.deepcopy.go, pkg/controller/servicebinding/mapper.go, pkg/controller/servicebinding/mapper_test.go, pkg/controller/servicebinding/reconciler.go, pkg/controller/servicebinding/sbrcontroller_test.go, pkg/controller/servicebinding/servicebinder_test.go, pkg/controller/servicebinding/servicecontext_test.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/service_binding.py, test/acceptance/features/steps/steps.py, test/mocks/mocks.go
https://issues.redhat.com/browse/APPSVC-696
`make test-acceptance VERBOSE=3`
=> Make services a required field in sbr spec

deploy/crds/operators.coreos.com_servicebindings_crd.yaml, pkg/apis/operators/v1alpha1/servicebinding_types.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/steps/steps.py
Making spec a required field
https://issues.redhat.com/browse/APPSVC-711
=> Make spec a required field in SBR

test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/steps.py, test/acceptance/features/unbindAppToService.feature
Fixes https://issues.redhat.com/browse/APPSVC-694
Note: The functionality given in the test is not available in this PR.  There is a separate issue #701 created for the same.
Test is disabled for now.
=> Add test for unbind an application from a service

OWNERS
Thanks for making valuable contributions @qibobo . Looking forward to more collaboration, discussions, and reviews  :confetti_ball:  :rocket:
=> Adding qibobo as a reviewer

examples/route_k8s_resource/README.md
Currently the example contains installation steps for the PostgreSQL DB operator but that is not used in the example at all, so it is useless.
Also it also uses the Node.js application used in the other examples, but that does not add any value for the example and only complicates it. The application can be just a simple Deployment.
And finally, the example uses `service-binding-demo` namespace so it is added to all `kubectl` commands so it is clear that those should all happen in that namespace.
This PR:
* Removes useless installation of PostgreSQL DB operator.
* Replaces the Node.js application with just a Deployment of `openshift/hello-openshift' image
* Polishes the `kubectl` commands
Follow the steps in the `route_k8s_resource` example
=> Fix route_k8s_resource example

test/acceptance/features/examples.feature, test/acceptance/features/steps/steps.py
JIRA TICKET: https://issues.redhat.com/browse/APPSVC-708
=> Add acceptance test to verify `route_k8s_resource` example

examples/nodejs_postgresql_namespaces/README.md, test/acceptance/features/examples.feature, test/acceptance/features/steps/steps.py
JIRA TICKET: https://issues.redhat.com/browse/APPSVC-706
=> Add acceptance test scenario to verify `nodejs_postgresql_nameaces` example

test/acceptance/features/bindAppToServiceUsingSecret.feature
Verifies GH issue #646 
JIRA TICKET: https://issues.redhat.com/browse/APPSVC-762
=> Add acceptance test: Verify pulling data from a secret living in another namespace

Makefile
=> Set version to 0.4.0

.travis.yml, examples/pod_spec_path/README.md, test/acceptance/features/examples.feature, test/acceptance/features/injectSecretAtCustomSchemaPath.feature
JIRA TICKET: https://issues.redhat.com/browse/APPSVC-707
=> Add acceptance test for PodSpec path example

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Ref. https://issues.redhat.com/browse/APPSVC-787
=> Update contributing guide with code of coduct

test/acceptance/features/bindAppToServiceUsingSecret.feature
https://github.com/redhat-developer/service-binding-operator/issues/808
https://issues.redhat.com/browse/APPSVC-785
=> Add acceptance test to verify collection of secrets from secretRef

README.md
Community calls have been updated, add new meeting link in the README.
=> Update Community Call in the README

README.md
=> Fix broken link to user guide

pkg/binding/model.go, pkg/binding/spec_test.go, test/acceptance/features/bindAppToServiceUsingConfigMap.feature, test/acceptance/features/bindAppToServiceUsingSecret.feature
=> Fix: use sourceKey to extract value from ConfigMap/Secret

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
The upstream project is supported by SBO Community
Change the support entity
NA
=> Change the support provider to SBO Community

pkg/reconcile/pipeline/builder/pipeline.go, pkg/reconcile/pipeline/handler/collect/impl.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, test/acceptance/features/bindAppToServiceUsingSecret.feature, test/acceptance/features/steps/steps.py
=> Add support for Direct Secret reference

docs/User_Guide.md
Wrong markdown format in user guide
**How?** title fixed.
N/A
=> Fix markdown format in User_Guide.md

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
In the OpenShift console, display name helps the user to identify the API name.
Set displaName attribute.
Fixes #1007
=> Set display name for spec CRD

config/rbac/role.yaml, controllers/common.go, test/acceptance/features/bindAppToProvisionedService.feature, test/acceptance/features/steps/app.py, test/acceptance/features/steps/generic_testapp.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/service_binding.py
* Adding additional cluster role for the service account is not needed anymore.
* Acceptance test added
Fixes #1025
=> Allow binding to OpenShift deployment configs out of the box

apis/conditions.go, pkg/reconcile/pipeline/handler/project/impl.go, test/acceptance/features/bindAppToService.feature, test/acceptance/features/injectBindingsAsFiles.feature, test/acceptance/features/steps/steps.py
Issue #1030
Do not bind as files if there is no binding data is collected from the service
=> Do not bind if there is no binding item collected from the service

pkg/reconcile/pipeline/builder/pipeline.go, pkg/reconcile/pipeline/builder/pipeline_test.go
If a panic happens while reconciling service binding, put the binding back in the queue and retry again
Fixes crashing loop reported in #1024
=> handle panics occurring in reconsile pipeline gracefuly

README.md, test/acceptance/features/injectSecretAtCustomSchemaPath.feature
Follows up to #1034
This PR:
* Removes all references to the examples removed via #1034
* Fixes #1042
=> Remove references to removed examples

test/acceptance/features/bindAppToServiceAnnotations.feature
#888 Suggests some scenarios to be covered in acceptance tests. The nested arguments scenario as suggested is not covered by any current acceptance test.
This PR:
* Enhances one of the scenarios with binding annotations for nested arguments as suggested in #888
PR checks should do
=> test(acceptance): add annotations with nested attributes into scenario for CRD annotations

docs/community-release.md, hack/prepare-operatorhub-pr.sh
=> Update obsoleted release instructions

Makefile
Done in preparation for the v1.0.1 release.
=> Bump version to v1.0.1

CONTRIBUTING.md
=> Add instruction to run tests

README.md
=> Update additional resources:Added Service Binding Operator Blog and Drag&Drop JAR and Service Binding

README.md
Updating the readme file with the link to the latest blog  on SBO
=> Updating the readme file with the link to the latest blog  on SBO

Makefile, test/performance/.gitignore, test/performance/collect-kpi.sh, test/performance/collect-metrics.sh, test/performance/collect-results.sh, test/performance/deploy-sbr.sh, test/performance/install-operators.sh, test/performance/kpi.py, test/performance/kpidiff.py, test/performance/run.sh, test/performance/setup.sh, test/performance/user-workloads/incomplete/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/invalid/sbo-test.sbr.yaml, test/performance/user-workloads/invalid/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/invalid/sbo-test.without-sbr.user-workloads.yaml, test/performance/user-workloads/valid/sbo-test.sbr.yaml, test/performance/user-workloads/valid/sbo-test.with-sbr.user-workloads.yaml, test/performance/user-workloads/valid/sbo-test.without-sbr.user-workloads.yaml
=> Add performance testing framework

test/performance/setup.sh
=> Install pre-built latest version of sandbox for the performance test.

Makefile, antora-playbook.yaml
Adds a feature to publish different version of the docs.
=> docs: publish different version of the docs

docs/ci.md
This PR:
* Updates CI related docs
- [*] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
=> Update CI docs.

charts/service-binding-operator/Chart.yaml
This PR adds service binding operator icon to metadata.
=> Add SBO icon to chart metadata

docs/userguide/modules/binding-workloads-using-sbo/pages/binding-options.adoc
Fixes up some documentation regarding label selection (thanks @Srivaralakshmi!)
=> docs: fixups for label selection

OWNERS
Adds @shruthihub as both an approver and a reviewer for SBO.
=> owners: add @shruthihub as approver & reviewer

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
Done in preparation for the v1.1.0 release
Signed-off-by: shruthihub <shruthi.shruthz@gmail.com>
=> Bump version to v1.1.0

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
=> Add description and displayName to ClusterWorkloadResourceMapping in CSV

Dockerfile
=> Change operator image baseimage to Red Hat's minima UBI 8

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
Done in preparation for the v1.1.1 release
Depends on: https://github.com/redhat-developer/service-binding-operator/pull/1171
=> Bump version to v1.1.1

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/clusterrole.yaml, charts/service-binding-operator/templates/clusterrolebinding.yaml, charts/service-binding-operator/templates/deployment.yaml
This PR list changes made on chart with sbo 1.1.1 app version
=> Update chart with sbo 1.1.1 app version

.github/actions/setup-podman/opm, .github/workflows/pr-checks-build-images.yaml, make/build.mk, make/common.mk
Fixes: https://github.com/redhat-developer/service-binding-operator/issues/1180
This PR:
* Changes the index image to be file-based
=> Change quay.io/redhat-developer/servicebinding-operator:index image to file-based catalog

.github/workflows/pr-checks.yaml, docs/userguide/modules/exposing-binding-data/pages/adding-annotation.adoc, pkg/binding/annotationmapper.go, pkg/binding/definition.go, pkg/binding/definition_test.go, pkg/binding/mocks/mocks.go, pkg/binding/model.go, pkg/binding/registry/registry.go, pkg/reconcile/pipeline/handler/collect/impl.go, pkg/reconcile/pipeline/handler/collect/impl_test.go, test/acceptance/features/bindAppToServiceAnnotationsOptional.feature
=> Enable annotations mapping to be optional

test/acceptance/features/environment.py
Signed-off-by: shruthihub <shruthi.shruthz@gmail.com>
=> Delete namespace after every scenario

.github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks-clean-images.yaml, .github/workflows/pr-checks-push-images.yaml, .github/workflows/pr-checks.yaml, .github/workflows/pr-labels.yaml
=> Enable PR checks on release branches

.github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks-clean-images.yaml, .github/workflows/pr-checks-push-images.yaml, .github/workflows/pr-checks.yaml, .github/workflows/pr-labels.yaml
=> cherry-pick(release-v1.1.x): Enable PR checks on release branches

.github/workflows/merge-to-release-branch.yaml
=> Add merge-to-release-branch GH workflow

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
=> Bump Version 1.2.0 (#1212)

CONTRIBUTING.md
=> Document labels used for issues

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
=> cherry-pick(release-v1.2.x): Update operator manifests with spec v1beta1

test/performance/collect-results.sh
=> cherry-pick(release-v1.2.x): Fix result collecting script in performnace test

make/version.mk
=> Bump vesion to 1.2.1

CONTRIBUTING.md, README.md
Fix typos in README.md and CONTRIBUTING.md files
=> Fix typos in documentation

OWNERS
=> Add filariow as an owner

antora-playbook.github.yaml, antora-playbook.local.yaml, make/version.mk
=> cherry-pick(release-v1.3.x): Bump version to v1.3.0

test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/supportExistingOperatorBackedServices.feature
=> cherry-pick(release-v1.2.x): Ensure the desired install plan is approved in acceptance tests

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
This PR updates the charts directory with service binding operator 1.3.0 chart.
=> cherry-pick(release-v1.3.x): update chart with 1.3.0

test/acceptance/features/supportSpecBeta1Resources.feature
`Project a v1beta1 service binding using a v1beta1 workload mapping` scenario is present twice in exact copies.
This PR removes the duplicate scenario.
=> Remove duplicate scenario

test/acceptance/features/supportSpecBeta1Resources.feature
`Project a v1beta1 service binding using a v1beta1 workload mapping` scenario is present twice in exact copies.
This PR removes the duplicate scenario.
=> cherry-pick(release-v1.3.x): Remove duplicate scenario

OWNERS
=> remove shruthihub as an owner

make/version.mk
=> Bump version to v1.3.1

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
=> bump SBO helm chart to v1.3.1

test/_projects/api-client/go.mod, test/_projects/api-controller/go.mod
When running `make test`, these versions are getting updated.
=> Update versions of dependencies

OWNERS
=> cherry-pick(release-v1.2.x): remove shruthihub as an owner

OWNERS
=> cherry-pick(release-v1.1.x): remove shruthihub as an owner

OWNERS
=> cherry-pick(release-v1.3.x): remove shruthihub as an owner

.github/workflows/pr-checks-build-images.yaml, .github/workflows/pr-checks.yaml, .gitignore, hack/upgrade-sbo-env.sh, make/acceptance.mk, make/build.mk, make/version.mk, test/acceptance/features/environment.py, test/acceptance/features/steps/environment.py, test/acceptance/features/steps/olm.py, test/acceptance/features/steps/openshift.py, test/acceptance/features/steps/servicebindingoperator.py, test/acceptance/features/steps/steps.py, test/acceptance/features/steps/util.py, test/acceptance/features/upgradeSBOwithOLM.feature
This PR:
* Updates the PR index image to have 2 bundles, the "latest master" from the `quay.io/redhat-developer/servicebinding-operator:index` image and the PR bundle image itself set to replace the "latest master" version.
* Includes a PR commit ID in the PR bundle version
* Depends on https://github.com/openshift/release/pull/33433
=> Test upgrade SBO with OLM

antora-playbook.github.yaml, antora-playbook.local.yaml
=> docs: Align docs branches to release branches

make/version.mk
=> Bump version to v1.3.2

config/manifests/bases/service-binding-operator.clusterserviceversion.yaml
=> Add displayName and description to older versions of owned CRDs in CSV

docs/devguide/modules/install-sbo/partials/openshift/intro.adoc
=> Fix external link in devguide documentation

.github/workflows/pr-checks.yaml, apis/webhooks/validator.go, pkg/reconcile/pipeline/context/impl.go, pkg/reconcile/pipeline/mapping.go, test/_projects/api-controller/main.go
/kind test
This adds [`gosec`](https://github.com/securego/gosec) as a static analysis tool, which does security checks directly on source code and matches for CWEs.  This also fixes its warnings on our current code.
=> add gosec security checks

pkg/reconcile/pipeline/context/service/crd_test.go, pkg/reconcile/pipeline/context/service/service.go, test/acceptance/resources/backend_crd.yaml
=> cherry-pick(release-v1.3.x): Detect bindable resource based on status attribute

make/version.mk
=> Bump version to v1.3.3

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
=> Bump version to v1.3.3 for helm chart

make/performance.mk, test/performance/collect-kpi.sh, test/performance/requirements.txt, test/performance/upload_data.py
This PR cherry-picks the following PRs from `master`:
* Adding support to upload performance kpi data to opensearch (#1331)
* Fixed the environment issue in CI (#1335)
* Added metadata with performance kpi data upload (#1363)
=> cherry-pick(release-v1.3.x): #1331, #1335 and #1363 for latest changes in the performance test

test/acceptance/features/gettingStartedGuide.feature, test/acceptance/features/supportExistingOperatorBackedServices.feature
This PR is a dependency of https://github.com/openshift/release/pull/35524
=> Disable scenarios not supported for OCP v4.12 also for OCP v4.13

test/performance/requirements.txt, test/performance/upload_data.py
=> Bump opensearch-py to v2.1.1

.github/workflows/periodic-security-check.yaml
Currently, the security scan is executed only for PRs and when PRs are merged.
This PR:
* Adds a periodic workflow that runs the security vulnerability scans for `master` branch daily to be able to spot the vulnerabilities earlier.
=> Add daily workflow to check for security vulnerabilities regularly

OWNERS
=> Remove @jasperchui as owner

README.md
Update the community meeting cadence in README.md
=> Update community meeting in README.md

.github/workflows/pr-cherry-picks.yaml
Adds automation for the v1.4.x release series.
=> add cherry pick action for v1.4.x release branch

test/acceptance/features/steps/openshift.py
This was causing test failures in CI.
/kind bug
=> test: retry app creation on failure

charts/service-binding-operator/Chart.yaml, charts/service-binding-operator/templates/deployment.yaml
=> bump helm chart to v1.4.1

README.md, docs/userguide/modules/ROOT/pages/intro.adoc
=> announce deprecation
